### PR TITLE
Update Meson to 1.5.0

### PR DESCRIPTION
**Pull request by ibc**
I've seen some `-undefined not supported` error when trying to build worker tests with Address Sanitizer in macOS (which is not supported anyway) and it went away after updating Meson.

### CODE REVIEW

**Comment by ibc** [comment]
Another relevant thing: I see this logs when building `worker-test-asan-address`:

```
meson.build:483: WARNING: Trying to use address sanitizer on Clang with b_lundef.
This will probably not work.
Try setting b_lundef to false instead.
```

I see this: https://github.com/mesonbuild/meson/issues/764

> If I don't specify `-Db_lundef=false` at the same time I specify `-Db_sanitize=address` I get linker errors when building shared objects.

I've added that argument c8e6af4fbc217f0dbc587cf8a49aa403e1ec74a7 but CI also fails: https://github.com/versatica/mediasoup/actions/runs/9820251862/job/27114630579?pr=1424

**Comment by ibc** [comment]
@nazar-pc any thoughts?

**Comment by ibc** [comment]
### CI passes with Meson 1.3.1

https://github.com/versatica/mediasoup/actions/runs/9977383351/job/27571866342?pr=1424

**Comment by nazar-pc** [comment]
Haven't tinkered with Meson for a while, but if you see unexpected CI issues, their Matrix channel is quite active, worth asking them why things worked in 1.3.1 and do not work in 1.4.1 even though it was supposed to be backwards compatible.

**Comment by ibc** [comment]
### CI passes with Meson 1.3.2

https://github.com/versatica/mediasoup/actions/runs/9977703991/job/27572958142?pr=1424

**Comment by ibc** [comment]
### CI fails with Meson 1.4.1 (also using gcc)

- gcc: https://github.com/versatica/mediasoup/actions/runs/9978006980/job/27573935859?pr=1424
- clang: https://github.com/versatica/mediasoup/actions/runs/9978006980/job/27573936387?pr=1424

**Comment by ibc** [comment]
### CI fails with Meson 1.4.2 (also using gcc)

- gcc: https://github.com/versatica/mediasoup/actions/runs/9978208727/job/27574561218?pr=1424
- clang: https://github.com/versatica/mediasoup/actions/runs/9978208727/job/27574561869?pr=1424

**Comment by ibc** [comment]
### CI fails with Meson 1.5.0 (also using gcc)

- gcc: https://github.com/versatica/mediasoup/actions/runs/9978359671/job/27575090848?pr=1424
- clang: https://github.com/versatica/mediasoup/actions/runs/9978359671/job/27575091841?pr=1424

**Comment by ibc** [comment]
@jmillan, I've updated the PR description with the CI result using all newer versions of Meson. Nothing valuable IMHO. We need to ask Meson devs.

**Comment by ibc** [comment]
Something I wanna check:

`mediasoup-worker.yaml` CI runs `invoke -r worker test` (which always passes) and then it runs `invoke -r worker test-asan-address`.

Logs in CI (example: https://github.com/versatica/mediasoup/actions/runs/9978006980/job/27573934209?pr=1424) show this:

```
> Run invoke -r worker test-asan-address

cd "/home/runner/work/mediasoup/mediasoup/worker" && "/home/runner/work/mediasoup/mediasoup/worker/out/pip_meson_ninja/bin/meson" setup --prefix "/home/runner/work/mediasoup/mediasoup/worker/out/Release" --bindir "" --libdir "" --buildtype release -Db_ndebug=true  -Db_sanitize=address -Db_lundef=false "/home/runner/work/mediasoup/mediasoup/worker/out/Release/build"
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
Run "meson setup --reconfigure to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
cd "/home/runner/work/mediasoup/mediasoup/worker" && "/home/runner/work/mediasoup/mediasoup/worker/out/pip_meson_ninja/bin/meson" setup --prefix "/home/runner/work/mediasoup/mediasoup/worker/out/Release" --bindir "" --libdir "" --buildtype release -Db_ndebug=true  "/home/runner/work/mediasoup/mediasoup/worker/out/Release/build"
Directory already configured.
```

Is there any chance for source code not being compiled from scratch (so `-Db_sanitize=address` is not applied somehow) and that makes things fail later when running tests (with ASAN) for whatever inconsistency? Not sure about this since logs below the above ones clearly show that the whole code is compiled (including subprojects).

**Comment by ibc** [comment]
Surprise coming.

**Comment by ibc** [comment]
Fixed!

https://github.com/versatica/mediasoup/actions/runs/9988859254/job/27606237014?pr=1424

**Pull request merged**
