### PR TITLE
fix strange rtp header padding

### PR DESCRIPTION
**Pull request by buptlsp**
refer to https://github.com/versatica/mediasoup/issues/1073

### CODE REVIEW

**Comment by ibc** [comment]
Why have you closed this PR @buptlsp?

**Comment by buptlsp** [comment]
I have mentioned this issue for more than 2 weeks, but no one has replied to me. Maybe you guys don't think it's important, but in reality it affects our company a lot money per day. So I had to change it privately. if you guys merge again, I need extra time to fix conflict.

I probably don't have enough confidence that you guys will think this is right. after all I've only been studying webrtc and c++ for a few months.

**Comment by buptlsp** [comment]
I solved the last problem with https://github.com/versatica/mediasoup/issues/1022.  but it's too complicated to create a pr, I have change a lot of places in private.  mybe I should close the issue first?

**Comment by jmillan** [comment]
> I have mentioned this issue for more than 2 weeks, but no one has replied to me. Maybe you guys don't think it's important,

Please have some patience. This project is maintained mostly out of working hours. Meaning we cannot always just leave everything and review the PRs as they come.

**Comment by jmillan** [comment]
Closing the PR because there has been no response is not the way to go. You can kindly ask for feedback if you find you didn't get response in a reasonable time period though.

**Comment by jmillan** [comment]
Also, in the meantime you can be the one telling us:

* "I've tested and it works as expected"
* "It does not imply any performance penalty / It does imply some performance penalty" etc.

Reviewing a PR that you've already tested and with which you have some confidence also helps the reviewing process.

**Comment by buptlsp** [comment]
Well, I'll be more patient next time. I actually found some other issues, and I'll submit pr when I've confirmed them.

This pr is in grey testing. I have wrote the problems I found  in the review. I'll resubmit when I have done my testing.

**Comment by ibc** [comment]
> I have mentioned this issue for more than 2 weeks, but no one has replied to me. Maybe you guys don't think it's important, but in reality it affects our company a lot money per day. So I had to change it privately. if you guys merge again, I need extra time to fix conflict.

Literally we have spent a week off due to work and we are super busy with many things (some of them indeed related to mediasouop). Please, more patient next time ;)

**Comment by ibc** [comment]
BTW these kind of changes definitely need fuzzer testing (see `mediasoup/docs/Fuzzer.md`).

**Pull request closed without merging**
