### PR TITLE
fix rr report

### PR DESCRIPTION
**Pull request by penguinol**
Previous code is as follow:
```
uint32_t newLostInterval     = (worstRemoteFractionLost * expectedInterval) >> 8;
uint32_t newReceivedInterval = expectedInterval - newLostInterval;
this->reportedPacketLost += (receivedInterval - newReceivedInterval);
```
When consumer franction lost >> producer fraction lost, (receivedInterval - newReceivedInterval) is ok.
But when consumer franction lost is only a litte bit higher than producer fraction lost,  (receivedInterval - newReceivedInterval) will be very small even if both consumer franction lost and producer fraction are very large.

### CODE REVIEW

**Comment by ibc** [comment]
@jmillan can you please take a look to this? My eyes are not good at this.

**Comment by jmillan** [comment]
I need to look at this with caution too :-)

**Review by jmillan — APPROVED** [review]
It's totally correct.

Thanks!

**Comment by ibc** [comment]
Nice, let's merge.

**Comment by ibc** [comment]
Thanks @penguinol!

**Pull request merged**
