### PR TITLE
Do not run test-asan-undefined in CI Linux GCC and upgrade abseil-cpp to 20240722.0 LTS

### PR DESCRIPTION
**Pull request by ibc**
## Details

- Skip `test-asan-undefined` in Linux with GCC due to a bug in GCC that affects abseil-cpp: https://github.com/abseil/abseil-cpp/issues/1634
- Unblock PR https://github.com/versatica/mediasoup/pull/1456 written by @garrettboone.

### CODE REVIEW

**Review by nazar-pc — APPROVED** [review]
Makes sense to me if CI passes

**Review by jmillan — APPROVED** [review]

**Comment by ibc** [comment]
This is insane, no idea what to do about this: https://github.com/versatica/mediasoup/actions/runs/11161680552/job/31024743216?pr=1457

**Comment by garrettboone** [comment]
> This is insane, no idea what to do about this: https://github.com/versatica/mediasoup/actions/runs/11161680552/job/31024743216?pr=1457

I think this command needs the Db_sanitize flag removed:

```
cd "/home/runner/work/mediasoup/mediasoup/worker" && "/home/runner/work/mediasoup/mediasoup/worker/out/pip_meson_ninja/bin/meson" setup --prefix "/home/runner/work/mediasoup/mediasoup/worker/out/Release" --bindir "" --libdir "" --buildtype release -Db_ndebug=true -Db_sanitize=undefined "/home/runner/work/mediasoup/mediasoup/worker/out/Release/build"
```

Here
https://github.com/versatica/mediasoup/blob/df0074b5b04ef17d7034f555b862a77d38e094cf/.github/workflows/mediasoup-node.yaml#L27

**Comment by ibc** [comment]
> > This is insane, no idea what to do about this: https://github.com/versatica/mediasoup/actions/runs/11161680552/job/31024743216?pr=1457
> 
> I think this command needs the Db_sanitize flag removed:
> 
> ```
> cd "/home/runner/work/mediasoup/mediasoup/worker" && "/home/runner/work/mediasoup/mediasoup/worker/out/pip_meson_ninja/bin/meson" setup --prefix "/home/runner/work/mediasoup/mediasoup/worker/out/Release" --bindir "" --libdir "" --buildtype release -Db_ndebug=true -Db_sanitize=undefined "/home/runner/work/mediasoup/mediasoup/worker/out/Release/build"
> ```
> 
> Here
> 
> https://github.com/versatica/mediasoup/blob/df0074b5b04ef17d7034f555b862a77d38e094cf/.github/workflows/mediasoup-node.yaml#L27

Good catch, will fix later.

**Comment by ibc** [comment]
> Good catch, will fix later.

Later means next week, but it will happen.

**Comment by ibc** [comment]
CI is green after suggested changes. Thanks @garrettboone. Will release a version soon.

**Pull request merged**
