### PR TITLE
fix: panic with normal errors in Rust

### PR DESCRIPTION
**Pull request by satoren**
Returns an error when an error can be returned

### CODE REVIEW

**Review by nazar-pc — COMMENTED** [review]
Did you actually hit this? If so then under which condition?
This is the kind of error that we indeed do not expect unless I missed something.

**Comment by satoren** [comment]
It is defined as a `RequestError`. Seems to be returning it except here. The type is also ` Result<ConsumerStats, RequestError>`. 

https://github.com/versatica/mediasoup/blob/d534be0cf3a90a7199435deb601dba73401bd767/rust/src/worker.rs#L46

**Comment by nazar-pc** [comment]
IIRC `ConsumerGetStatsRequest` never errors, it is just ignored if consumer doesn't exist. No strong opinion though.

**Comment by ibc** [comment]
So should we merge or not?

**Review by nazar-pc — APPROVED** [review]
Sure, I don't think it will ever happen, but it doesn't hurt either

**Comment by satoren** [comment]
I have encountered the [L1042](https://github.com/versatica/mediasoup/blob/e4d90d9398f357cefac67e0616c9fa5cd9e28099/rust/src/router/consumer.rs#L1041) panic, but I don't know up to the exact cause because there is no other information available.

Maybe it is an error that the "Channel already closed".

**Pull request merged**
