### PR TITLE
SimulcastConsumer::GetDesiredBitrate(): Choose the highest bitrate among all Producer streams

### LINKED ISSUE #989: Inconsistency of Sending Bitate with Available Outgoing Bitrate
During my work on BWE backport branch, I have noticed that mediasoup sometimes sends at higher bitrate than that which is reported by BWE algorithm. I tried to make this reproducible as much as possible so the setup is next: mediasoup-demo consumerReplicas branch running on the localhost, with two browser tabs opened on the same machine. Tab1: produce=false&consumerReplicas=19. Tab2: consumer=false&consumerReplicas=19. So we have single producer that produces simulcast stream, and 20 consumers replicas on the other side. Inside Trasnport.cpp I have hardcoded available bitrate to be 60 Mbps, it is never changing. Despite that this is what can be seen on graphs:
image

It seems that it correlates with packet loss:
image

In the same time RTX bitrate is relatively small to explain such a big gap:
image

webrtc-internals send side:
image

webrtc-internals receive side:
image

Distribution of available bitrate seems to be fine per logs: https://pastebin.com/inTDYp2Q, but actual sending bitrate is not.

chrome://webrtc-intenals for one of this cases:  https://drive.google.com/file/d/1nvciwm9SW3KAUjAPHCQtMbQN9fs2YKar/view?usp=sharing

### PR DESCRIPTION
**Pull request by ibc**
Instead of assuming that the highest simulcast stream is the one consuming highest bitrate, iterate all them and pick up the highest value.

This is because when the sender enables a higher stream, initially the bitrate of it could be less than the bitrate of a lower stream. In a few seconds it will become higher. However don't report its irrelevant current bitrate in the meantime.

*NOTE:* This PR is not intended to fix https://github.com/versatica/mediasoup/issues/989

### CODE REVIEW

**Comment by ibc** [comment]
@nazar-pc I strongly think we should freeze Rust version in mediasoup-rust to avoid these unexpected and totally unrelated CI errors: https://github.com/versatica/mediasoup/actions/runs/4023390642/jobs/6914204443

**Review by jmillan — APPROVED** [review]
Makes sense.

**Review by nazar-pc — APPROVED** [review]
Sure, I'll add config that locks the version so we can update it manually. These changes are easy to fix though, just run `cargo clippy --all-targets` and fix things until it stops complaining.

The changes here make sense to me.

**Comment by ibc** [comment]
Problem is that cargo clippy works for me in my computer. How should I update Rust? Via brew install rust? Or brew install cargo?

**Comment by nazar-pc** [comment]
New version was out yesterday with new lints enabled by default: https://blog.rust-lang.org/2023/01/26/Rust-1.67.0.html
Updating can be done easily with `rustup update`.

**Comment by ibc** [comment]
@nazar-pc I need help here:
CleanShot-2023-01-27-at-12 25 50@2x

**Comment by ibc** [comment]
> @nazar-pc I need help here: CleanShot-2023-01-27-at-12 25 50@2x

Trying to apply this change:

```diff
--- a/rust/src/worker.rs
+++ b/rust/src/worker.rs
@@ -500,8 +500,7 @@ impl Inner {
                     Err(error) => Err(io::Error::new(
                         io::ErrorKind::Other,
                         format!(
-                            "unexpected first notification from worker [id:{}]: {:?}; error = {}",
-                            id, notification, error
+                            "unexpected first notification from worker [id:{id}]: {notification}; error = {error}"
                         ),
                     )),
                 };
```

**Comment by ibc** [comment]
I've tried this(as per output help):
CleanShot-2023-01-27-at-12 30 09@2x
then it complains again with:
CleanShot-2023-01-27-at-12 30 46@2x

**Comment by nazar-pc** [comment]
It was `{:?}`, which is print debug version of the data, not regular (`{}`), so it should be `{notification:?}`:
```rust
                        format!(
                            "unexpected first notification from worker [id:{id}]: {notification:?}; \
                            error = {error}"
                        ),
```

When strings are longer than configured length formatter gives up formatting other code around it sometimes, so better splitting it into multiple lines explicitly in those cases.

UPD: Error message actually suggested `:?`, I guess you overlooked it due to 2 other variables.

**Comment by ibc** [comment]
Thanks @nazar-pc, pushed. Should be green now.

**Comment by nazar-pc** [comment]
Rust is not happy with your skills today, sir. Use `cargo clippy --all-targets` at the root of the repo in case you run it under `rust` only

**Comment by ibc** [comment]
Did `cargo clippy --all-targets` ignore `rust/tests` folder because I executed it in `rust` folder? WHAT? How can be this language legal?

**Comment by nazar-pc** [comment]
I don't think that was the case, tests are covered by that command.
CI just runs that command in the root of the repo and refuses to accept any warnings.
I think you're close though.

**Comment by ibc** [comment]
CleanShot-2023-01-27-at-14 11 35@2x

CleanShot-2023-01-27-at-14 12 00@2x

Really???

**Comment by nazar-pc** [comment]
Only plain variables can be used, not expressions or property accesses like `self.id`. Let me fix those for you and push a commit into this branch.

**Comment by ibc** [comment]
All fixed in last commit.

**Comment by ibc** [comment]
This error didn't show locally: https://github.com/versatica/mediasoup/actions/runs/4024845039/jobs/6917332591

**Comment by nazar-pc** [comment]
> This error didn't show locally: https://github.com/versatica/mediasoup/actions/runs/4024845039/jobs/6917332591

Because it is platform-specific code. Unless you're on Windows, it is not compiled.

`rust-toolchain.toml` will make sure `cargo` downloads and uses desired version of Rust toolchain and components necessary for operation, including for CI to run successfully. There should be no guessing or mismatched tooling versions anymore.

**Comment by ibc** [comment]
> `rust-toolchain.toml` will make sure `cargo` downloads and uses desired version of Rust toolchain and components necessary for operation, including for CI to run successfully. There should be no guessing or mismatched tooling versions anymore.

amazing

**Comment by nazar-pc** [comment]
All :green_circle:

**Pull request merged**
