### PR TITLE
Use more efficient collections

### PR DESCRIPTION
**Pull request by jmillan**
Extracted from `memory-optimizations` branch to make it more readable and concise.

### CODE REVIEW

**Review by ibc — APPROVED** [review]
If it works I assume this is better

**Comment by nazar-pc** [comment]
I had first 5 commits from that PR extracted into https://github.com/nazar-pc/mediasoup/tree/more-efficient-data-structures

**Comment by jmillan** [comment]
> I had first 5 commits from that PR extracted

IMHO the smaller and more specific PRs the better.  Otherwise reviewing them is too complicated. These two commits do just modify the containers. 

Do you suggest doing this any other way @nazar-pc ?

**Comment by nazar-pc** [comment]
My branch just replaces more containers, that is the only difference. I have nothing against landing this one.

**Comment by jmillan** [comment]
> My branch just replaces more containers, that is the only difference.

These 2 commits do not touch the logic. One of those 5 commits deletes unused unrelated code, another one touches the one byte RTP extensions code. Splitting them into different PRs will facilitate the review, make it easier adding a specific test if needed,  and git bisect in case there is need for troubleshoot in the future.

I would be grateful if you could create different PRs out of that branch, or I can also do it myself if you prefer.

**Review by nazar-pc — APPROVED** [review]

**Pull request merged**
