### PR TITLE
Cleanup remaining payload channel references

### PR DESCRIPTION
**Pull request by jmillan**

### CODE REVIEW

**Review by nazar-pc — APPROVED** [review]
This will require minor version bump for `mediasoup-sys` due to change in public API

**Comment by ibc** [comment]
Rationale please?

**Comment by nazar-pc** [comment]
Cargo will be happy to install compatible (according to semver) version of the package that is newer than technically required. Since arguments changed, older `mediasoup` will no longer be compatible with newer `mediasoup-sys`. So instead of increasing patch version we have to increase minor version to prevent breaking changes for people.

**Comment by jmillan** [comment]
It can be merged since the minor version has been increased here https://github.com/versatica/mediasoup/pull/1324

**Pull request merged**
