### PR TITLE
Handle soft errors gracefully

### PR DESCRIPTION
**Pull request by nazar-pc**
In Rust all of the communication with worker is heavily asynchronous and even multi-threaded, there is no direct way to guarantee order of messages except creating an explicit queue. This sometimes leads to situations where consumer is closed after transport (since everything is dropped and multiple close requests are racing for completion on worker with each other and might be delivered in any order) for instance.

Such situations produce unhelpful error messages that these changes will suppress and turn into success. If something tries to close consumer that doesn't exist on worker anyway, it is now treated as successful completion (similarly to idempotent HTTP method `DELETE`).

### CODE REVIEW

**Comment by Hartigan** [comment]
@nazar-pc  ```Consumer::get_stats``` generates many errors too, even with ```Consumer::closed``` checks. Will all such ```consumer not found``` be fixed?

**Comment by nazar-pc** [comment]
I don't think so. Racing during closing is something that user of the library doesn't control. The rest is user-controlled, so should be preventable. I don't recall immediately why producer isn't owned by consumer so it is not closed automatically, maybe I'll add that later. For something like `get_stats` there isn't really a reasonable default value to return either.

Having heavier typing for errors would be nice, but that might be a lot of work.

**Review by ibc — APPROVED** [review]

**Comment by nazar-pc** [comment]
Merging as is for now, I'll see what other improvements can be done about similar situations

**Comment by jmillan** [comment]
:+1:

**Pull request merged**
