### PR TITLE
fix asan error for new-delete-type-mismatch

### PR DESCRIPTION
**Pull request by satoren**
This handle seems to be of type `uv_pipe_t`.

### CODE REVIEW

**Review by jmillan — CHANGES_REQUESTED** [review]
indeed `handle` is of type `uv_stream_t*`.

**Comment by ibc** [comment]
> indeed `handle` is of type `uv_stream_t*`.

Nope, it's `uv_pipe_t*`:

```c++
err = uv_shutdown(
      req, reinterpret_cast<uv_stream_t*>(this->uvHandle), static_cast<uv_shutdown_cb>(onShutdown));
```

In .hpp:

```hpp
uv_pipe_t* uvHandle{ nullptr };
```

So PR is ok IMHO.

**Comment by jmillan** [comment]
> Nope, it's uv_pipe_t*:

I verified that `shutdown_t->handle` is a `uv_stream_t*`. Probably that's casted from `uv_pipe_t*`, but I'm not sure.

If ASAN is not complaining then :+1:

**Review by jmillan — APPROVED** [review]

**Comment by ibc** [comment]
> > Nope, it's uv_pipe_t*:
> 
> 
> 
> I verified that `shutdown_t->handle` is a `uv_stream_t*`. Probably that's casted from `uv_pipe_t*`, but I'm not sure.
> 
> 
> 
> If ASAN is not complaining then :+1:

uv_pipe is a subtype of uv_stream. uv_tcp as well.

**Comment by ibc** [comment]
Let's not merge yet, I want to check something.

**Comment by ibc** [comment]
It's ok. Merging. Thanks @satoren. But the same should be done in `TcpConnectionHandle.cpp`, I will do it in a separate PR.

**Comment by ibc** [comment]
> It's ok. Merging. Thanks @satoren. But the same should be done in `TcpConnectionHandle.cpp`, I will do it in a separate PR.

Done here: https://github.com/versatica/mediasoup/commit/08bdf564ed4210d14437d6102b879020265191c2

**Pull request merged**
