### PR TITLE
Update modules structure and other minor improvements for Rust version

### PR DESCRIPTION
**Pull request by nazar-pc**
Changes:
* Refactored modules structure: it still looks the same to developers and docs, but doesn't confuse IDE as much so autocomplete works well
* `NonClosingProducer` renamed to `PipeProducer` with better documentation about why it exists (old name is still available)
* Minor fix in libmediasoup-worker that avoids printing irrelevant messages

I will update changelog and bump versions in upcoming PRs once macOS support is merged upstream (hopefully very soon).

### CODE REVIEW

**Review by jmillan — COMMENTED** [review]
I don't know Rust myself, but the changes seem to enhance readability and inline documentation.

Considering tests pass I'm OK with the PR.

**Comment by nazar-pc** [comment]
Pushed an update to fix some of the lints.

Do you plan to update libwebrtc to fix `numeric_limits` issues in CI with Ubuntu 18.04/20.04 and Clang (if it does fix it)?
Looks like an import is missing of something like that.

**Comment by jmillan** [comment]
> Do you plan to update libwebrtc to fix numeric_limits issues in CI with Ubuntu 18.04/20.04 and Clang (if it does fix it)?

The problem is within the abseil dependency used by libwebrtc. I Don't think we want to clone it just to avoid this issue, since also there are being some efforts to remove libwebrtc completely from mediasoup.

**Review by ibc — APPROVED** [review]
I don't see any bad words in the changes so I assume it's ok. Merging.

**Pull request merged**
