### PR TITLE
Use more than one core for compilation on Windows

### PR DESCRIPTION
**Pull request by nazar-pc**
MinGW is what we expect people to use right now on Windows, so this should do the trick

### CODE REVIEW

**Review by ibc — APPROVED** [review]

**Comment by ibc** [comment]
How can clang linter fail here? 😐

**Comment by nazar-pc** [comment]
Hm... looks like clang-format was updated in the package we use

**Comment by nazar-pc** [comment]
Reinstalled locally and applied new rules. Please take a look, maybe you'll want to tweak formatter settings now.

**Comment by ibc** [comment]
It's ok, thanks

**Pull request merged**
