### PR TITLE
add cmake support

### PR DESCRIPTION
**Pull request by johzzy**
base git@github.com:barry-ran/mediasoup.git

### CODE REVIEW

**Comment by ibc** [comment]
Which is the motivation of this PR? Is it just a cosmetic change?

**Comment by johzzy** [comment]
> Which is the motivation of this PR? Is it just a cosmetic change?

for step-by-step operation, but now it is all submitted.

**Comment by nazar-pc** [comment]
I see OpenSSL was updated, if that is updated it should be done in a separate PR to make this one much smaller.

**Comment by johzzy** [comment]
> Which is the motivation of this PR? Is it just a cosmetic change?



> I see OpenSSL was updated, if that is updated it should be done in a separate PR to make this one much smaller.

splitted.

**Comment by nazar-pc** [comment]
> splitted.

This PR still contains changes related to congestion control and over 200k LoC of changes, which as you can imaging is not reviewable as is.

It would be nice to have just OpenSSL upgrade separately in its own PR and CMake changes separately, so that OpenSSL upgrade can be verified separately and it is clear what changes are needed for CMake itself, which I would imagine isn't quite as big as 200k LoC.

**Pull request closed without merging**
