### PR TITLE
More SRTP crypto suites

### LINKED ISSUE #835: Support more SRTP cipher suites
## Feature Request

We currently support these:
* SRTP_AES128_CM_HMAC_SHA1_80
* SRTP_AES128_CM_HMAC_SHA1_32

We should also support more modern and more secure options:
* SRTP_AEAD_AES_128_GCM
* SRTP_AEAD_AES_256_GCM

Someone was already asking about this on the forum, I think it is time to make it happen.

### PR DESCRIPTION
**Pull request by ibc**
Fixes #835

- Node and Rust: Add missing 'AEAD_AES_256_GCM' and 'AEAD_AES_128_GCM' in `SrtpCryptoSuite` type.
- `PlainTransport`: Enable usage of 'AEAD_AES_256_GCM' and 'AEAD_AES_128_GCM' (however 'AES_CM_128_HMAC_SHA1_80' remains being the default suite if not specified).
- `PipeTransport`: Use 'AEAD_AES_128_GCM' instead of 'AES_CM_128_HMAC_SHA1_80'.

NOTE: I've also done changes in the website/API (not published yet, of course).

### CODE REVIEW

**Comment by ibc** [comment]
@nazar-pc are there changes required in Rust? Note that I had to modify some tests in Node.

**Comment by ibc** [comment]
> @nazar-pc are there changes required in Rust? Note that I had to modify some tests in Node.

C'mon, I can run `cargo test` and see.

**Review by nazar-pc — COMMENTED** [review]
This looks fine to me, but similar changes to tests and `SrtpCryptoSuite` data structure in Rust are needed as well

**Comment by ibc** [comment]
> This looks fine to me, but similar changes to tests and `SrtpCryptoSuite` data structure in Rust are needed as well

on it

**Comment by ibc** [comment]
@nazar-pc, Rust code updated :)

**Review by nazar-pc — APPROVED** [review]
Looks good assuming CI passes :+1:

**Comment by nazar-pc** [comment]
Please do `cargo fmt` to apply standard Rust formatting to the code

**Comment by ibc** [comment]
> Please do `cargo fmt` to apply standard Rust formatting to the code
CleanShot-2022-06-19-at-16 27 28@2x

Help :(

**Comment by nazar-pc** [comment]
Hm... I guess it is homebrew again. Is there `cargo-fmt` available for installation. It is typically a part of the default package with rustup...

**Comment by ibc** [comment]
Nope, no `cargo-fmt` command available.

**Comment by ibc** [comment]
I've made the changes manually. Let's see CI result.

**Comment by nazar-pc** [comment]
I have no idea what incomplete version of Rust toolchain Homebrew ships :disappointed: 

You can try `rustfmt path/to/file`, `cargo fmt` just formats the whole project with a single command.

**Comment by nazar-pc** [comment]
Turns out if you don't want to install rustup directly (no idea why not) you can install it with brew:
```
brew install rustup-init
```

Then with `rustup-init` you should be able to install proper Rust+Cargo (I think) with full config instead of what you have right now.

**Comment by ibc** [comment]
> Turns out if you don't want to install rustup directly (no idea why not) you can install it with brew:
> 
> ```
> brew install rustup-init
> ```
> 
> Then with `rustup-init` you should be able to install proper Rust+Cargo (I think) with full config instead of what you have right now.

Not sure if I understand, how to install Rust and Cargo after installing `rustup-init`?

**Comment by ibc** [comment]
ok, I see

**Comment by nazar-pc** [comment]
Just run `rustup-init` and agree to install stable version

**Comment by ibc** [comment]
wow!
CleanShot-2022-06-19-at-16 42 15@2x

**Comment by ibc** [comment]
`cargo fmt` working :)

**Pull request merged**
