### PR TITLE
Fix build error of Rust version on M1 mac

### PR DESCRIPTION
**Pull request by satoren**
Require Command line tools for Xcode

### CODE REVIEW

**Comment by nazar-pc** [comment]
Hm, the idea was to have a static build of the library, which was the reason to download LLVM and download libc++ from it.

I'm not sure it makes much difference though as realistically macOS will only be used for testing/development, not for production. And having 2 branches, one for x86-64 and another for AArch64 probably isn't worth it :thinking:

**Comment by nazar-pc** [comment]
There is warning in macOS build:
> warning: cargo:rustc-cdylib-link-arg was specified in the build script of mediasoup-sys v0.2.5 (/Users/runner/work/mediasoup/mediasoup/worker), but that package does not contain a cdylib target


I guess that argument is not needed?

**Comment by satoren** [comment]
Removed it.

**Comment by satoren** [comment]
> I'm not sure it makes much difference though as realistically macOS will only be used for testing/development, not for production.

I think so too. And I can not found `clang+llvm-12.0.0-aarch64-apple-darwin` in https://github.com/llvm/llvm-project/releases

**Review by nazar-pc — APPROVED** [review]
Makes sense to me, thank you!

**Pull request merged**
