### PR TITLE
Introduce OwnedWebRtcMessage

### PR DESCRIPTION
**Pull request by RemiKalbe**
Not sure if it's the best way to solve #1007 but it compiles and passes the tests.

### CODE REVIEW

**Comment by nazar-pc** [comment]
Why don't you clone in event handler instead? In some cases you don't need to clone things, so can avoid allocation. This basically forces allocation for everyone all the time.

**Comment by RemiKalbe** [comment]
Could you point me to where event handler is ? I don't know the codebase well enough 😅

**Comment by nazar-pc** [comment]
In `on_message` in https://github.com/versatica/mediasoup/issues/1007 try `.into_owned()` rather than `.clone()`

**Comment by RemiKalbe** [comment]
```
no method named `into_owned` found for reference `&WebRtcMessage<'_>` in the current scope
method not found in `&WebRtcMessage<'_>`
```
To I need to have some trait in scope ?

**Comment by nazar-pc** [comment]
I mean you'll need to match on enum and then to `.into_owned()` on the contents.

Though I'm not opposed to the latest version of changes in this PR, but can you replace `to_vec` with `into_owned`? It seems more idiomatic to me.

**Comment by RemiKalbe** [comment]
Oh yeah right 😅, I did not think about that!

**Comment by nazar-pc** [comment]
The reason of such behavior here is efficiency: the memory slice you're getting is most likely allocated by C++ worker. If you process it right away, you don't need to re-allocate it somewhere. But if you want to move it to another thread then yes, you need to clone it and get owned value.

**Comment by RemiKalbe** [comment]
Got it ! Thanks for the explanation 👍

**Comment by ibc** [comment]
Should we close #1007 then?

**Comment by nazar-pc** [comment]
Yes, it was essentially a question, there was nothing to fix, but this PR makes it a bit more convenient

**Pull request merged**
