### PR TITLE
Add `Send` to async trait of `RtpObserver`

### PR DESCRIPTION
**Pull request by RemiKalbe**
Remove the `(?Send)` constraint on `async_trait` so It can be sent between threads.
Related to https://mediasoup.discourse.group/t/rust-future-created-by-async-block-is-not-send/3977/3

### CODE REVIEW

**Review by nazar-pc — APPROVED** [review]

**Review by ibc — APPROVED** [review]

**Comment by ibc** [comment]
There is a rust thing failing in CI: https://github.com/versatica/mediasoup/runs/5377836891?check_suite_focus=true

**Comment by RemiKalbe** [comment]
I don't see how my PR made the CI fail, the error doesn't seem related 🤔

**Comment by nazar-pc** [comment]
Looks like something on GitHub started listening on those ports all of a sudden?..

**Comment by RemiKalbe** [comment]
Can the failing check be restarted?

**Comment by nazar-pc** [comment]
Yes, just did

**Comment by RemiKalbe** [comment]
It seems like it's working 😂

**Comment by ibc** [comment]
@nazar-pc that is why we use pick-port library in Node tests 😀

**Comment by nazar-pc** [comment]
@ibc time to learn some Rust, PR is welcome :wink:

**Comment by ibc** [comment]
You got me here. A simple library that does a single thing and mimics the behavior of another lib. I'll do it but don't expect anything soon

**Comment by nazar-pc** [comment]
There may already be a library for this, try to search on crates.io

**Pull request merged**
