### PR TITLE
avgDBov conflict

### PR DESCRIPTION
**Pull request by buptlsp**
Background: 
- We use audioLevel to determine which producer's audio will be sent.
- mapDBovsProducer is a map that uses avgDBov as the key.
- avgDBov is an int value from -127 to 0. In fact, we will use threshold, which has a value from threshold to 0.

Facts:
When there are two producers in the router, their avgDBov within the interval may be the same (with probability 1/threshold), causing this producer to be overwritten by other producers. In this case, the sound of this producer will sound intermittent. The more producers in the room, the higher the probability of them colliding.

### CODE REVIEW

**Review by nazar-pc — COMMENTED** [review]
Lol, wondering why no one noticed this earlier :upside_down_face: 

One issue here though: `mapProducerDBovs` is btree_map, which is supposed to be sorted. I suspect it wasn't properly processed before (it preferred quietest 10 producers present), not it prefers 10 random producers (ordered by ID), not loudest.

**Comment by nazar-pc** [comment]
The solution here is likely to store a vector of producers, not a single one. Also iteration should likely be in reverse order, so we pick up to 10 loudest producers.

**Comment by ibc** [comment]
> The solution here is likely to store a vector of producers, not a single one. Also iteration should likely be in reverse order, so we pick up to 10 loudest producers.

I need to remember what we are supposed to store here. The 10 Producers with highest audio level?

**Comment by ibc** [comment]
> I suspect it wasn't properly processed before (it preferred quietest 10 producers present)

Nope. It's iterated from highest to lowest keys:

```c++
for (; idx < this->maxEntries && rit != mapDBovsProducer.crend(); ++idx, ++rit)
```

NOTE: I'm not saying there is no issue. Of course there is.

**Comment by nazar-pc** [comment]
> Nope. It's iterated from highest to lowest keys:

Indeed, read the wrong line, you're right.

**Comment by ibc** [comment]
We should use `absl::btree_multimap` right?

**Comment by nazar-pc** [comment]
Yeah, I think so

**Comment by ibc** [comment]
Closing in favour of https://github.com/versatica/mediasoup/pull/1021.
Thanks for reporting, @buptlsp

**Pull request closed without merging**
