### PR TITLE
Add transport.setMinOutgoingBitrate() (2)

### PR DESCRIPTION
**Pull request by ibc**
Same PR than https://github.com/versatica/mediasoup/pull/1035/files by @jcague (all credits to him) with some additions such as the ability to reset min/max limits by calling the methods with argument 0 and more tests.

### CODE REVIEW

**Comment by ibc** [comment]
Off-topic: @nazar-pc the Meson issue when fetching libs is today more annoying than 1 year ago. Are you aware of any progress in whichever side it corresponds? I'm basically restarting failing workflows like crazy.

**Comment by nazar-pc** [comment]
Looks like libuv website is down, returns 500 to me :man_shrugging: 

Would be great to have some reliable caching server/CDN in Meson, especially since everything is checked against contents hashes.

**Comment by ibc** [comment]
> Looks like libuv website is down, returns 500 to me 🤷‍♂️

Which URL? I tried the failing one and worked for me.

> Would be great to have some reliable caching server/CDN in Meson, especially since everything is checked against contents hashes.

But that's not something we can do.

**Comment by ibc** [comment]
@nazar-pc please help here, I do NOT understand why this Rust test is failing: https://github.com/versatica/mediasoup/actions/runs/4553997834/jobs/8031278488?pr=1038

**Comment by ibc** [comment]
> @nazar-pc please help here, I do NOT understand why this Rust test is failing: https://github.com/versatica/mediasoup/actions/runs/4553997834/jobs/8031278488?pr=1038

Ignore, missing `cargo fmt`.

**Comment by nazar-pc** [comment]
I tried this:
> https://dist.libuv.org/dist/v1.44.2/libuv-v1.44.2.tar.gz

Must be flaky today

**Comment by ibc** [comment]
> I tried this:
> 
> > https://dist.libuv.org/dist/v1.44.2/libuv-v1.44.2.tar.gz
> 
> Must be flaky today

I can download it reliably :(

**Comment by ibc** [comment]
@jcague this is released in 3.11.17 (in 5-10 minutes).

**Pull request merged**
