### PR TITLE
worker: handle SIGILL signal in *nix

### PR DESCRIPTION
**Pull request by ibc**
As discussed in https://mediasoup.discourse.group/t/hardware-exceptions-handling-in-mediasoup-workers/.

**TODO:** Unclear whether `std::_Exit(EXIT_FAILURE)` is needed in the SIGILL signal hander. Probably not.

**TODO:** No idea how to do the Windows stuff since `__except (EXCEPTION_EXECUTE_HANDLER)` does not receive the exact error, so I cannot print it as we currently do.
   **NOTE:** May be done, see PR code.

### CODE REVIEW

**Comment by snnz** [comment]
> **TODO:** No idea how to do the Windows stuff since `__except (EXCEPTION_EXECUTE_HANDLER)` does not receive the exact error, so I cannot print it as we currently do.

There is an exact error, it is just stored in some structure that is not accessed directly, but through the `GetExceptionCode` function (actually a macro): https://docs.microsoft.com/en-us/windows/win32/debug/getexceptioncode
It covers quite a lot of possible errors. And then there is GetExceptionInformation function that provides more information about an exception, rather technical.

**Comment by ibc** [comment]
Can you provide example code of using those macros to print error name/message/info as we do now on the catch()?

**Comment by ibc** [comment]
I don't understand anything. I see things like this and I don't know how to deal with them:

```c++
} __except (ExceptionFilter (GetExceptionInformation (), GetExceptionCode ())) {
```

NOTE: I don't have Windows.

**Comment by ibc** [comment]
Ok, this may be done. Can you review @snnz?

BTW I'd also need help with this:

> **TODO:** Unclear whether `std::_Exit(EXIT_FAILURE)` is needed in the *unix SIGILL signal hander. Probably not.

See [here](https://github.com/versatica/mediasoup/pull/498/files#diff-f15b6b2f6a023cdae80e1bd4b4f994deaa515a18c700cc250e1baa7d4a633c6fR271).

**Comment by snnz** [comment]
SEH (structural exception handling) is not a complete replacement for the regular C++ exception handling, so in Windows, it is better to leave try/catch blocks as they are, including the one in main(), but move all code that is currently in main into a separate function, and envelope its call in __try/__except that will catch exceptions unhandled by C++ RTL (separate functions for try/catch and __try/__except are necessary to avoid using expensive /EHa option).

Here is the sketch:

```
#ifndef _WIN32
  int main()
#else
  int win32_main()
#endif
  {
     try
     {
        ...
     }
     catch
     {
        ...
     }
  }

#ifdef _WIN32
  int main()
  {
    ___try
    {
       return win32_main();
    }
    ___except (EXCEPTION_EXECUTE_HANDLER)
    {
       // Report exception
    }
  }
#endif
```

Getting intelligible messages for the codes returned by GetExceptionCode() is rather tricky, because normal formatting of these errors is broken (believe it or not, they haven't fixed it for the past 25+ years!). If something more than just a bare code is necessary, then here is the way to do this:

```
#include <windows.h>
#include <tchar.h>

DWORD FormatNtStatus(ULONG nsCode, LPTSTR* ppszMessage)
{
	auto hNtDll = LoadLibrary(_T("NTDLL.DLL"));
	if (!hNtDll) return 0;
	typedef ULONG(*RtlNtStatusToDosErrorProc)(ULONG Status);
	auto RtlNtStatusToDosError = (RtlNtStatusToDosErrorProc)GetProcAddress(hNtDll, "RtlNtStatusToDosError");
	auto n = FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_FROM_HMODULE, hNtDll, RtlNtStatusToDosError(nsCode), MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPTSTR)ppszMessage, 0, NULL);
	FreeLibrary(hNtDll);
	return n;
}
```

And then, for example:

```
int main()
{
	__try
	{
		int *p = nullptr;
		return *p;
	}
	__except (EXCEPTION_EXECUTE_HANDLER)
	{
		LPTSTR pszMessage;
		if (FormatNtStatus(GetExceptionCode(), &pszMessage))
		{
			_fputts(pszMessage, stderr);
			LocalFree(pszMessage);
		}
		else _ftprintf(stderr, _T("Exception: 0x%08lX\n"), GetExceptionCode());
	}

}
```

will write something like "Invalid access to memory location".

**Comment by snnz** [comment]
> **TODO:** Unclear whether `std::_Exit(EXIT_FAILURE)` is needed in the SIGILL signal hander. Probably not.

I am not that familiar with POSIX signal handling, but don't standards (POSIX and C) say that if handler function returns normally when handling SIGFPE, SIGILL or SIGSEGV, the behavior is undefined?

**Comment by ibc** [comment]
Closing due to inactivity.

**Pull request closed without merging**
