### PR TITLE
fix(worker build): CLT version detect exception

### PR DESCRIPTION
**Pull request by enimo**
XCode **Command Line Tools** info no longer show up when call `CLTVersion() ->  /usr/sbin/pkgutil` on Catalina (OS X 10.15), which break off the XcodeVersion detection with an exception **"gyp: No Xcode or CLT version detected!"** .

This patch adds a additional method to detect CLT version based on **Software Update** history: `/usr/sbin/softwareupdate` .

### CODE REVIEW

**Comment by ibc** [comment]
Wow, do you mean that mediasoup cannot be compiled on Mac OS Catalina? and this PR fixes it? If so, thanks a lot.

We plan to move from gyp to CMake (since gyp is no longer maintained) but this is good to have in the meanwhile.

Can you confirm that this is exactly as I understand?

**Comment by enimo** [comment]
Yes, it can be reproduced on OS X 10.15.5 (Catalina) while executing command `/usr/sbin/pkgutil` which called in `pylib/gyp/xcode_emulation.py`. And my mediasoup-worker compiled successfully after modify.

**Comment by ibc** [comment]
Thanks. Will merge and release a new version in next days when we also do some more pending stuff.

**Review by ibc — APPROVED** [review]

**Comment by ibc** [comment]
@enimo did you actually check if the latest `gyp` version also fixes this issue? I've run `scripts/get-dep.sh gyp` (within the mediasoup `worker` folder) and I get changes from `gyp` upstream that also affects this topic, and if possible we prefer to keep the upstream version to avoid having to maintain our own version of `gyp`.

**Comment by ibc** [comment]
@enimo those are the changes in gyp upstream project:

- https://chromium.googlesource.com/external/gyp.git/+/caa60026e223fc501e8b337fd5086ece4028b1c6

I've applied them to mediasoup `v3`, which means your previous PR has been replaced. Can you please test mediasoup v3 in Catalina and see if it compiles or if your changes are needed again?

**Comment by enimo** [comment]
@ibc ok, i will test it again.

**Comment by ibc** [comment]
Thanks. BTW I've asked people with Mac Catalina and it works for them. Actually it did work even before your PR and also after my latest change (which overrides your PR).

**Comment by enimo** [comment]
@ibc The build exception still popped up which locate to `XcodeVersion() -> pylib/gyp/xcode_emulation.py` and verbose output below:

> npm-scripts.js [INFO] running task "postinstall"
> npm-scripts.js [INFO] executing command: make -C worker
> /usr/bin/python2 ./scripts/configure.py -R mediasoup-worker
> ['-R', 'mediasoup-worker', 'demo/node_modules/mediasoup/worker/mediasoup-worker.gyp', '-I', 'demo/node_modules/mediasoup/worker/common.gypi', '--depth=.', '-f', 'make', '-Goutput_dir=demo/node_modules/mediasoup/worker/out', '--generator-output', 'demo/node_modules/mediasoup/worker/out', '-Dgcc_version=110', '-Dclang=1', '-Dhost_arch=x64', '-Dtarget_arch=x64', '-Dopenssl_fips=', '-Dmediasoup_asan=false', '-Dnode_byteorder=little']
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance [ignored]
> 
> Traceback (most recent call last):
>   File "./scripts/configure.py", line 111, in <module>
>     run_gyp(gyp_args)
>   File "./scripts/configure.py", line 49, in run_gyp
>     rc = gyp.main(args)
>   File "./deps/gyp/pylib/gyp/__init__.py", line 545, in main
>     return gyp_main(args)
>   File "./deps/gyp/pylib/gyp/__init__.py", line 530, in gyp_main
>     generator.GenerateOutput(flat_list, targets, data, params)
>   File "./deps/gyp/pylib/gyp/generator/make.py", line 2210, in GenerateOutput
>     part_of_all=qualified_target in needed_targets)
>   File "./deps/gyp/pylib/gyp/generator/make.py", line 820, in Write
>     self.Pchify))
>   File "./deps/gyp/pylib/gyp/generator/make.py", line 1215, in WriteSources
>     cflags = self.xcode_settings.GetCflags(configname)
>   File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 630, in GetCflags
>     archs = self.GetActiveArchs(self.configname)
>   File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 488, in GetActiveArchs
>     xcode_archs_default = GetXcodeArchsDefault()
>   File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 120, in GetXcodeArchsDefault
>     xcode_version, _ = XcodeVersion()
>   **File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 1411, in XcodeVersion**
>     version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
> AttributeError: 'NoneType' object has no attribute 'groups'
> make: *** [default] Error 1

My OS X version is 10.15.5 (upgrade a week ago), and I already installed xcode Command Line Tools (CLT), but without install Xcode App ( two separated applications). Is it the detection error caused by this condition.

**Comment by ibc** [comment]
Ah, I see. So the thing is that you do NOT have XCode installed. I did not even know that it may work without XCode installed. Clear now.

Would you mind please create the PR again on top of the updated `v3` branch? I tried to figure out how to update it but no idea about Python.

**Comment by enimo** [comment]
@ibc Okay, I'll create it again.

**Comment by ibc** [comment]
Thanks a lot.

**Pull request merged**
