### PR TITLE
Revert "fix: Workaround for tsc error"

### PR DESCRIPTION
**Pull request by satoren**
Because it was fixed in upstream https://github.com/facebook/jest/releases/tag/v27.4.3

### CODE REVIEW

**Review by nazar-pc — APPROVED** [review]
Nice

**Review by ibc — COMMENTED** [review]
I don't see jest dependency being updated in package.json...

**Comment by nazar-pc** [comment]
> I don't see jest dependency being updated in package.json...

But we don't have lock file either (or else CI wouldn't break in the first place)

**Comment by ibc** [comment]
Right but I always try to keep versions in package.json up to date 😀

Don't worry, I'll update it eventually.

**Pull request merged**
