### PR TITLE
fix CLT/xcode version detection exception

### PR DESCRIPTION
**Pull request by enimo**
fix(worker build): CLT version detect exception without XCode install, more details refers to #410

### CODE REVIEW

**Review by ibc — APPROVED** [review]

**Comment by ibc** [comment]
Thanks.

**Comment by ibc** [comment]
Released in 3.6.4.

**Comment by ibc** [comment]
BTW good work here. Indeed it seems that mediasoup did not even install in Mojave if XCode was not installed: https://mediasoup.discourse.group/t/worker-process-failed-pid-undefined/1169/10

**Comment by enimo** [comment]
Glad to hear this :)

**Pull request merged**
