### PR TITLE
Move TS and JS to node/ folder and and use ES private fields

### PR DESCRIPTION
**Pull request by ibc**
- Add `node` folder and move TypeScript and compiled JavaScript code to it.
- Also move `tests` folder, `.eslintrc.js` and `tsconfig.json`.
- Some minor cosmetic changes.
- Add Nazar into `contributors` field in `package.json`.
- Node: use ES6 private fields.
- Require Node >= 12.

### CODE REVIEW

**Comment by ibc** [comment]
How are those conflicts possible? :-(

**Comment by nazar-pc** [comment]
I think `meson` branch didn't include changes from #667

**Comment by ibc** [comment]
Ohh that's. Ok I'll resolve them.

**Comment by ibc** [comment]
@nazar-pc help please. In theory I've done anything, however when I run `npm test` I get this error:

```
../../meson.build:246:0: ERROR: Subproject exists but has no meson.build file
```

[meson-log.txt](https://github.com/versatica/mediasoup/files/7317842/meson-log.txt)

**Comment by nazar-pc** [comment]
I'm sorry, but I accidentally pushed 1 commit fc5835f9834dfcfe925b69818b95fd3f17c8dc9f to `v3` branch directly, it should fix the issue for you.
Basically it found Catch2 on your system and tried to build with CMake, but failed. fc5835f9834dfcfe925b69818b95fd3f17c8dc9f will make sure to always use Catch2 from Meson dependencies.

**Comment by ibc** [comment]
Ok, I'll cherry pick, thanks.

**Comment by ibc** [comment]
Closing in favour of https://github.com/versatica/mediasoup/pull/673

**Pull request closed without merging**
