### PR TITLE
[flatbuffers] Fix CI in node 20

### PR DESCRIPTION
**Pull request by ibc**
Same as https://github.com/versatica/mediasoup-client/pull/283

### CODE REVIEW

**Comment by ibc** [comment]
Next in a new PR I'm gonna remove `mediasoup.version` getter. It's a complete hack (in involves `fs.writeFileSync()` in JS transpiled files in `node/lib` folder). I know this is a breaking change since `mediasoup.version` is a public getter but I think we can live with it. @nazar-pc @jmillan thoughts?

**Comment by ibc** [comment]
So @nazar-pc suggest making `mediasoup.version` getter run `fs.readfileSync(path.join(__dirname__, '..', 'package.json')` and parse it and return the value of `version` field. It's an overkill IMHO.

**Comment by nazar-pc** [comment]
It is not a getter, it is a constant, so you'll need to do that in `(() => {})()` so it is called immediately.

This is a public API you've committed to, breaking it isn't nice. I'm not sure why people would use that field, but maybe a bit less bad alternative than removing it would be to fix it at soem value like current release and mark as deprecated for people to not rely on anymore.

**Comment by ibc** [comment]
I'll check keep it as it is. The issue is fixed in this PR so I won't complicate my life more than it is already. In v4 this will be removed.

**Pull request merged**
