### PR TITLE
[flatbuffers] Add pause() and resume() in DataProducer and DataConsumer

### PR DESCRIPTION
**Pull request by ibc**
NOTE: This PR targets `flatbuffers` branch.

### Details

- `pause()`and `resume()` in `DataProducer` and `DataConsumer`.
- `paused` getter in `DataProducer` and `DataConsumer`.
- `dataProducerPaused` getter in `DataConsumer`.
- `dataproducerpause` and `dataproducerresume` events in `DataConsumer`.
- `pause` and `resume` events in `DataProducer.observer` and `DataConsumer.observer`.
- `paused?: boolean` in `transport.consumeData()` and `transport.produceData()`.

### Bonus Tracks

- FBS: Rename `WEBRTC_TRANSPORT` to `WEBRTCTRANSPORT`, `DATA_PRODUCER` to `DATAPRODUCER`, etc etc everywhere.
- C++: Add some missing brackets here and there.

### CODE REVIEW

**Review by jmillan — APPROVED** [review]

**Comment by nazar-pc** [comment]
Why though? Seems less readable to me.

**Comment by ibc** [comment]
> Why though? Seems less readable to me.

Consistency. Majority won. It's easier if we don't use separators within entity/class names in FBS dictionaries.

**Comment by ibc** [comment]
@nazar-pc is this a bug? In `producer.rs`:

```rust
/// Callback is called when the producer is paused.
pub fn on_pause<F: Fn() + Send + Sync + 'static>(&self, callback: F) -> HandlerId {
    self.inner().handlers.pause.add(Arc::new(callback))
}
```

But nobody calls `on_pause()` in `Producer` instances:

```
$ ack on_pause
src/router.rs
1070:       pipe_consumer
1071:            .on_pause({

src/router/producer.rs
675:    pub fn on_pause<F: Fn() + Send + Sync + 'static>(&self, callback: F) -> HandlerId {

src/router/active_speaker_observer.rs
244:    fn on_pause(&self, callback: Box<dyn Fn() + Send + Sync + 'static>) -> HandlerId {

src/router/audio_level_observer.rs
255:    fn on_pause(&self, callback: Box<dyn Fn() + Send + Sync + 'static>) -> HandlerId {

src/router/rtp_observer.rs
72:    fn on_pause(&self, callback: Box<dyn Fn() + Send + Sync + 'static>) -> HandlerId;

src/router/consumer.rs
853:    pub fn on_pause<F: Fn() + Send + Sync + 'static>(&self, callback: F) -> HandlerId {
```

**Comment by ibc** [comment]
@nazar-pc @jmillan this is ready for review. Everything is done, including Rust. However, since Rust tests don't work yet in the flatbuffers branch so... but they should be ok.

**Comment by nazar-pc** [comment]
`on_pause` is for users, so they can attach a callback that will be triggered when producer is paused, I do not believe it is a bug.

**Comment by ibc** [comment]
I see. Thanks. Approve please 🙏

**Review by jmillan — APPROVED** [review]
:+1:

**Pull request merged**
