### PR TITLE
C++ cleanup

### PR DESCRIPTION
**Pull request by nazar-pc**
This just fixes a bunch of compiler warnings (not all of them, but still)

### CODE REVIEW

**Review by jmillan — APPROVED** [review]

**Comment by jmillan** [comment]
Which compiler is giving such warnings @nazar-pc, gcc?

**Review by ibc — APPROVED** [review]
thanks

**Comment by ibc** [comment]
> Which compiler is giving such warnings @nazar-pc, gcc?

Good question, because it's long time since I see any related warning using gcc and clang. Merging BTW.

**Comment by nazar-pc** [comment]
It is GCC. I'm experimenting with Meson build system, non-zero log level produces A LOT of warnings, this PR fixes a good bunch of those, but many still remain.

**Comment by nazar-pc** [comment]
These are what Meson enables with warnings level 1: `-Wall -Winvalid-pch -Wnon-virtual-dtor`

**Pull request merged**
