### PR TITLE
Producer scores for Consumers

### PR DESCRIPTION
**Pull request by ibc**
Solution for #420 

Make `ConsumerScore` include a new `producerScores` field:

```ts
export type ConsumerScore =
{
	/**
	 * The score of the RTP stream of the consumer.
	 */
	score: number;

	/**
	 * The score of the currently selected RTP stream of the producer.
	 */
	producerScore: number;

	/**
	 * The scores of all RTP streams in the producer.
	 */
	producerScores: number[];
}
```

This way, the consumer side can know what spatial layers are "alive" in the producer side.

CleanShot-2020-06-13-at-12 34 33

ezgif com-resize

### CODE REVIEW

**Comment by ibc** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- worker/src/RTC/SimulcastConsumer.cpp  1
- worker/src/RTC/SvcConsumer.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/versatica/mediasoup/pullRequest?prid=5678604&bid=18588858)

**Comment by ibc** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- worker/src/RTC/SvcConsumer.cpp  1
- worker/src/RTC/SimulcastConsumer.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/versatica/mediasoup/pullRequest?prid=5678604&bid=18588858)

**Comment by ibc** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- worker/src/RTC/SvcConsumer.cpp  1
- worker/src/RTC/SimulcastConsumer.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/versatica/mediasoup/pullRequest?prid=5678604&bid=18588858)

**Comment by ibc** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- worker/src/RTC/SvcConsumer.cpp  1
- worker/src/RTC/SimulcastConsumer.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/versatica/mediasoup/pullRequest?prid=5678604&bid=18588858)

**Comment by ibc** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- worker/src/RTC/SvcConsumer.cpp  1
- worker/src/RTC/SimulcastConsumer.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/versatica/mediasoup/pullRequest?prid=5678604&bid=18588858)

**Comment by ibc** [comment]
Ready, merging.

**Comment by ibc** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- worker/src/RTC/SimulcastConsumer.cpp  1
- worker/src/RTC/SvcConsumer.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/versatica/mediasoup/pullRequest?prid=5678604&bid=18588858)

**Comment by jmillan** [comment]
:+1:

**Pull request merged**
