### PR TITLE
fix srtp_steam leak when closing producer and consumers

### PR DESCRIPTION
**Pull request by penguinol**
#426

### CODE REVIEW

**Comment by ibc** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- worker/src/RTC/PlainTransport.cpp  4
- worker/src/RTC/WebRtcTransport.cpp  2
- worker/src/RTC/PipeTransport.cpp  4
         

Clones removed
==============
+ worker/include/RTC/WebRtcTransport.hpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/versatica/mediasoup/pullRequest?prid=5748280&bid=18811813)

**Comment by ibc** [comment]
Good catch. Let me take a look since I think the implementation could be a bit different (more simpler). On it. Will ping here soon.

**Comment by penguinol** [comment]
> Good catch. Let me take a look since I think the implementation could be a bit different (more simpler). On it. Will ping here soon.

Yes, the code is a little bit duplicate because srtp session is in the sub class.

**Comment by ibc** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- worker/src/RTC/WebRtcTransport.cpp  2
- worker/src/RTC/PlainTransport.cpp  4
- worker/src/RTC/PipeTransport.cpp  4
         

Clones removed
==============
+ worker/src/RTC/Transport.cpp  -2
+ worker/include/RTC/WebRtcTransport.hpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/versatica/mediasoup/pullRequest?prid=5748280&bid=18811813)

**Comment by ibc** [comment]
@penguinol can you please take a look to https://github.com/versatica/mediasoup/pull/428? It's a simpler approach to achieve the same. I've tested it by also printing SRTP streams handled by libsrtp and it works as expected.

**Comment by jmillan** [comment]
Very nice catch @penguinol

**Comment by ibc** [comment]
Closing in favour of https://github.com/versatica/mediasoup/pull/428. thanks!

**Comment by penguinol** [comment]
> @penguinol can you please take a look to #428? It's a simpler approach to achieve the same. I've tested it by also printing SRTP streams handled by libsrtp and it works as expected.

Ok, i will test it next week. we have a festival next days.

**Comment by ibc** [comment]
Don't worry, it's tested, merged and released :)

**Pull request closed without merging**
