### PR TITLE
Allow passing sendBufferSize and recvBufferSize when creating transports (and add listenInfo everywhere)

### LINKED ISSUE #554: allow setting receive buffer size
## Feature Request

I see no way to set the UDP receive buffer size (i.e. SO_RCVBUF), which can be a problem when trying to ingest 'bursty' streams into a router. Would it make sense to add it?

### PR DESCRIPTION
**Pull request by ibc**
Fixes #554

*NOTE:* This branch was created from `flatbuffers` branch and we must wait for `flatbuffers` to be merged in `v3` before merging this PR.

### Details

- Add optional `sendBufferSize` and `recvBufferSize` (in bytes) in `WebRtcServerListenInfo` type in `ListenInfo` type (corresponding doc in libuv: https://docs.libuv.org/en/v1.x/handle.html?highlight=uv_send_buffer_size).
- Deprecate `ListenIp` type and allow passing `listenInfo(s)` in all `router.createXxxxTransport()`.

### Bonus Tracks

- Add `{ }` in more C++ condition blocks.
- Rename `handlers/XxxxHandler.xxx` to `handlers/XxxxHandle.xxx` becase those are "handles" rather than "handlers" (in fact they wrap a "libuv handle").

### CODE REVIEW

**Comment by jbaudanza** [comment]
I think we should consider differentiating the buffer sizes for UDP and TCP. Maybe a `udpRecvBufferSize` and `tcpRecvBufferSize` would be appropriate.

The WebRtcServer shares one buffer for all transports, so it's important for this to have a large buffer. For TCP, each transport will have a new socket with a new buffer, so the buffer size should be smaller.

Also, it would be good to have these options for PlainTransport and WebRtcTransport

**Comment by ibc** [comment]
> I think we should consider differentiating the buffer sizes for UDP and TCP. Maybe a `udpRecvBufferSize` and `tcpRecvBufferSize` would be appropriate.

Nope. In `WebRtcServerListenInfo` type you must specify `protocol`"udp" or "tcp", so no need for separate fields.

https://mediasoup.org/documentation/v3/mediasoup/api/#WebRtcServerListenInfo

> The WebRtcServer shares one buffer for all transports, so it's important for this to have a large buffer.

Here I assume you mean UDP, right?

> For TCP, each transport will have a new socket with a new buffer, so the buffer size should be smaller.

Here I have a question: When we listen in TCP we create a `TcpServer` which internally creates a libuv `uv_tcp_t` handle and we listen on it for incoming connections. Then for each connection we get a new libuv `uv_tcp_t` handle specific for his TCP connection and wrap it into a `TcpTransport` instance.

Where should we apply send/recv buffer sizes? in the `uv_tcp_t` of the `TcpServer` or in the `uv_tcp_t` of each `TcpConnection`?

> Also, it would be good to have these options for PlainTransport and WebRtcTransport

Yes, I want to validate work done in `WebRtcServer` first. This PR is still a draft.

**Comment by ibc** [comment]
> Here I have a question: When we listen in TCP we create a `TcpServer` which internally creates a libuv `uv_tcp_t` handle and we listen on it for incoming connections. Then for each connection we get a new libuv `uv_tcp_t` handle specific for his TCP connection and wrap it into a `TcpTransport` instance.
> 
> Where should we apply send/recv buffer sizes? in the `uv_tcp_t` of the `TcpServer` or in the `uv_tcp_t` of each `TcpConnection`?
> 
> >

@saghul explained me that this must be done in each TCP connection.

**Comment by jbaudanza** [comment]
> @saghul explained me that this must be done in each TCP connection.

Yeah that makes sense.

> Nope. In WebRtcServerListenInfo type you must specify protocol"udp" or "tcp", so no need for separate fields.

Got it. I missed that. My comment about differentiating UDP and TCP doesn't apply then.

> > For TCP, each transport will have a new socket with a new buffer, so the buffer size should be smaller.

> Here I assume you mean UDP, right?

Yes. But I don't think it's relevant anymore.

>> Also, it would be good to have these options for PlainTransport and WebRtcTransport

> Yes, I want to validate work done in WebRtcServer first. This PR is still a draft.

Got it. Looks good so far.

**Comment by jmillan** [comment]
I approve the buffer size changes. The naming changes will make the flatbuffers branch more difficult to review IMHO. Can they be done in V3 instead?

**Comment by ibc** [comment]
I'll spend LOT of time reviewing flatbuffers PR when finished. Doing these changes in v3 will generate tons of conflicts and will be hell to switch between branches etc.

**Comment by ibc** [comment]
Everything is done (but Rust side). It works in every kind transport, tested.

**Comment by jmillan** [comment]
> Doing these changes in v3 will generate tons of conflicts and will be hell to switch between branches etc.

I mean the rename of the handlers. That should no conflict with anything.

**Comment by ibc** [comment]
> > Doing these changes in v3 will generate tons of conflicts and will be hell to switch between branches etc.
> 
> I mean the rename of the handlers. That should no conflict with anything.

I convinced @jmillan by phone to let me do this just this time.

**Comment by ibc** [comment]
@nazar-pc can you help me with this Rust stuff please? I don't event understand what it means: https://github.com/versatica/mediasoup/actions/runs/4699601161/jobs/8333267093?pr=1052

Also, can you help me with this? It doesn't even compile: https://github.com/versatica/mediasoup/pull/1052/files#diff-7ec981d3b6b95cb6b794442fb129984e1230a3ea5f9209ec27cf39446e8e47f7L270

**Comment by ibc** [comment]
> Also, can you help me with this? It doesn't even compile: https://github.com/versatica/mediasoup/pull/1052/files#diff-7ec981d3b6b95cb6b794442fb129984e1230a3ea5f9209ec27cf39446e8e47f7L270

Fixed here: https://github.com/versatica/mediasoup/pull/1052/files#diff-7ec981d3b6b95cb6b794442fb129984e1230a3ea5f9209ec27cf39446e8e47f7R277

CleanShot-2023-04-14-at-17 30 03@2x

**Comment by ibc** [comment]
> @nazar-pc can you help me with this Rust stuff please? I don't event understand what it means: https://github.com/versatica/mediasoup/actions/runs/4699601161/jobs/8333267093?pr=1052

Issue also happens in `flatbuffers` branch: https://github.com/versatica/mediasoup/actions/runs/4701401995/jobs/8337381054?pr=1052

It doesn't happen to my in local. I've updated Rust/Cargo by running `brew install rustup-init` then running it as in the past:

```
> cargo --version
cargo 1.67.0 (8ecd4f20a 2023-01-10)

> rustc --version
rustc 1.67.0 (fc594f156 2023-01-24)
```

No idea which Rust/Cargo versions are being used in the CI. Didn't we do something to fix Rust version in mediasoup?

**Comment by ibc** [comment]
@jmillan when running `cargo test` in local in this branch (remember that this branch is based on `flatbuffers` branch) it miserably crashes as follows:

```
ibc at ibc-macbook-pro in ~/src/v3-mediasoup on add-send-recv-buffer-size-to-webrtcserver-listeninfos
$ KEEP_BUILD_ARTIFACTS=1 cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.81s
     Running unittests src/lib.rs (target/debug/deps/mediasoup-62bceade33552064)

running 27 tests
test ortc::tests::generate_router_rtp_capabilities_unsupported ... ok
test ortc::tests::generate_router_rtp_capabilities_too_many_codecs ... ok
test ortc::tests::generate_router_rtp_capabilities_succeeds ... ok
test ortc::tests::get_producer_rtp_parameters_mapping_unsupported ... ok
test data_structures::tests::dtls_fingerprint ... ok
test ortc::tests::get_producer_rtp_parameters_mapping_get_consumable_rtp_parameters_get_consumer_rtp_parameters_get_pipe_consumer_rtp_parameters_succeeds ... ok
Assertion failed: (cur_ >= scratAssertion failed: (ok), functionch_ && scratch_ >= buf_), function ensure_space, file vector_dow Required, file flatbuffer_buildnward.h, line 138.
er.h, line 1219.
Assertion failed: (ok), function Required, file flatbuffer_builder.h, line 1219.
error: test failed, to rerun pass `-p mediasoup --lib`

Caused by:
  process didn't exit successfully: `/Users/ibc/src/v3-mediasoup/target/debug/deps/mediasoup-62bceade33552064` (signal: 6, SIGABRT: process abort signal)
```

Is this expected? Or should I do something else to get mediasoup-rust tests pass?

**Comment by nazar-pc** [comment]
> Issue also happens in flatbuffers branch: https://github.com/versatica/mediasoup/actions/runs/4701401995/jobs/8337381054?pr=1052

Are you sure you're running `clippy` locally? In generally it is a bit irritating to see those `fmt` and similar messages, just configure your editor to apply `rustfmt` to edited files on safe automatically and use `cargo clippy --all-targets` to verify that things compile. Not only it is faster than `cargo build`, it also shows you all of those warnings you see in CI.

Error says exactly what it doesn't like and how to fix it.

> Is this expected? Or should I do something else to get mediasoup-rust tests pass?

Tests are not working, Rust support in `flatbuffers` is still ongoing, it barely does a few things for now.

**Comment by nazar-pc** [comment]
Can't run tests as a starting point, it crashes somewhere in C++ without useful backtrace:
```
nazar-pc@nazar-pc:/w/g/m/rust> cargo test --test integration -- worker
    Finished test [unoptimized + debuginfo] target(s) in 0.05s
     Running tests/integration/main.rs (/home/nazar-pc/.cache/cargo/target/debug/deps/integration-5eef5ea544617908)

running 6 tests
mediasoup-worker::mediasoup_worker_run() | settings error: dtlsCertificateFile: cannot read file '/notfound/cert.pem': No such file or directory
test worker::create_worker_wrong_settings ... ok
integration-5eef5ea544617908: ../../../../../../../../../../web/github/mediasoup/worker/subprojects/flatbuffers-23.3.3/include/flatbuffers/vector_downward.h:138: size_t flatbuffers::vector_downward::ensure_space(size_t): Assertion `cur_ >= scratch_ && scratch_ >= buf_' failed.
integration-5eef5ea544617908: ../../../../../../../../../../web/github/mediasoup/worker/subprojects/flatbuffers-23.3.3/include/flatbuffers/vector_downward.h:138: size_t flatbuffers::vector_downward::ensure_space(size_t): Assertion `cur_ >= scratch_ && scratch_ >= buf_' failed.
error: test failed, to rerun pass `--test integration`
```

There are a few different errors, sometimes it prints this:
```
integration-5eef5ea544617908: ../../../../../../../../../../web/github/mediasoup/worker/subprojects/flatbuffers-23.3.3/include/flatbuffers/flatbuffer_builder.h:342: void flatbuffers::FlatBufferBuilder::NotNested(): Assertion `!nested' failed.
integration-5eef5ea544617908: ../../../../../../../../../../web/github/mediasoup/worker/subprojects/flatbuffers-23.3.3/include/flatbuffers/flatbuffer_builder.h:385: flatbuffers::uoffset_t flatbuffers::FlatBufferBuilder::EndTable(flatbuffers::uoffset_t): Assertion `!ReadScalar<voffset_t>(buf_.data() + field_location->id)' failed.
integration-5eef5ea544617908: ../../../../../../../../../../web/github/mediasoup/worker/subprojects/flatbuffers-23.3.3/include/flatbuffers/flatbuffer_builder.h:342: void flatbuffers::FlatBufferBuilder::NotNested(): Assertion `!nested' failed.
integration-5eef5ea544617908: ../../../../../../../../../../web/github/mediasoup/worker/subprojects/flatbuffers-23.3.3/include/flatbuffers/flatbuffer_builder.h:342: void flatbuffers::FlatBufferBuilder::NotNested(): Assertion `!nested' failed.
```

UPD: Commented-out `create_worker_wrong_settings` test and getting this:
```
double free or corruption (out)
```

Okay, I think `static flatbuffers::FlatBufferBuilder bufferBuilder;` isn't going to work with multiple threads using it concurrently, this is likely why all of those things are happening with Rust :confused:

**Comment by nazar-pc** [comment]
Fixed memory-related issues in https://github.com/versatica/mediasoup/pull/1062, but there are still 2 issues I see:
1) Concerning number of warnings in C++ code
2) `npm test` is not possible to run twice in a row, it deletes compiled flatbuffers files and I have to run `npm run postinstall` every time before running tests, shouldn't really be necessary

**Comment by ibc** [comment]
> Are you sure you're running `clippy` locally? In generally it is a bit irritating to see those `fmt` and similar messages, just configure your editor to apply `rustfmt` to edited files on safe automatically and use `cargo clippy --all-targets` to verify that things compile. Not only it is faster than `cargo build`, it also shows you all of those warnings you see in CI.

:+1:

> Error says exactly what it doesn't like and how to fix it.

Well, if I apply what the error says then it complains locally because `_` is reserved. Anyway this is fixed after your commit in flatbuffers branch (I've merged it into this branch), so thanks.

**Comment by nazar-pc** [comment]
Can we wait merging this into `flatbuffers` until `flatbuffers` is merged into `v3`?
It is already hard to understand what has changed in there comparing to `v3`, adding more features on top will only make it even more difficult.

**Comment by ibc** [comment]
> Can we wait merging this into `flatbuffers` until `flatbuffers` is merged into `v3`? It is already hard to understand what has changed in there comparing to `v3`, adding more features on top will only make it even more difficult.

It's better to add new features or changes that involve worker channel changes into flatbuffers branch instead of v3, otherwise tons of conflicts. Yes, I can wait before merging this. Will change the **NOTE** above and make this ready for review.

**Comment by ibc** [comment]
@jmillan why have you closed this PR??

**Comment by jmillan** [comment]
> @jmillan why have you closed this PR??

OMG. So I've renamed `flatbuffers` branch to `flatbuffers-old` and removed the former. When deleting the old `flatbuffers` branch this PR has been automatically closed because `add-send-recv-bu..` branch is made on top of it.

**Comment by nazar-pc** [comment]
It is fine, just rebase against new `flatbuffers` with old commits dropped and reopen PR, edit to target a different branch

**Comment by ibc** [comment]
> It is fine, just rebase against new `flatbuffers` with old commits dropped and reopen PR, edit to target a different branch

What does it mean "with old commits dropped"?

**Comment by nazar-pc** [comment]
Old `flatbuffers` had hundreds of commits in it. Remove them all during rebase, leave just commits of this branch.

**Comment by ibc** [comment]
Closing this PR in favour of https://github.com/versatica/mediasoup/pull/1065.

**Pull request closed without merging**
