### PR TITLE
Test foo

### PR DESCRIPTION
**Pull request by ibc**
TEST: DELETE

This is basically same as v3 branch. This branch comes from https://github.com/versatica/mediasoup/pull/1442 PR in which all its commits have been reverted. Just to see if Rust tests also fail here.

### CODE REVIEW

**Comment by nazar-pc** [comment]
You know you can test CI without opening PRs, right?

**Comment by ibc** [comment]
> You know you can test CI without opening PRs, right?

Yes, but I may want to use this PR as temporal documentation. Well, tests will probably pass here which means that something in my PR broke things despite it looks incredible.

**Comment by nazar-pc** [comment]
> documentation

Could use a more creative title in this case :see_no_evil:

**Comment by ibc** [comment]
Ok, Rust tests pass in this branch which is basically v3. So no magic here. Something is broken in https://github.com/versatica/mediasoup/pull/1442. Closing this PR.

**Pull request closed without merging**
