### PR TITLE
Fix #492 SimulcastConsumer cannot switch layers if initial tsReferenc…

### LINKED ISSUE #492: SimulcastConsumer cannot switch layers if initial tsReferenceSpatialLayer disappears
## Bug Report

SimulcastConsumer cannot switch layers if initial tsReferenceSpatialLayer disappears

### Your environment

- Operating system: Linux (multiple)
- Node version:  N/A
- npm version: N/A
- gcc/clang version: N/A
- mediasoup version: 3.6.24, 3.6.29 (Probably since 3.6.17, but only tested those)
- mediasoup-client version: 3.6.11

### Issue description

The problem happens if the higher spatial layer is never resumed. For example:

* Start with 3 spatial layers
* SimulcastConsumer will select layer 2 for tsReferenceSpatialLayer and currentSpatialLayer. (I believe this is only since the change in 3.6.17 (SimulcastConsumer: Prefer the highest spatial layer initially (PR #450).)
* Client sets max spatial layer to 0 before any Sender Reports are sent. (And leaves it at this forever).
* SimulcastConsumer will eventually notice layer 2 as inactive and set currentSpatialLayer to -1, but the logic in CanSwitchToSpatialLayer will not allow any other layer to be selected since GetProducerTsReferenceRtpStream()->GetSenderReportNtpMs() will remain false.

### PR DESCRIPTION
**Pull request by Lynnworld**
…eSpatialLayer disappears

We found the same issue as #492 described . If we do't get initial tsReferenceLayer SR , we can't switch latter. 

Fixes #492

### CODE REVIEW

**Review by ibc — APPROVED** [review]
Love this PR. Thanks. Will merge next week and release.

**Comment by ibc** [comment]
@jmillan

**Comment by ibc** [comment]
Please add an entry in CHANGELOG file

**Review by jmillan — COMMENTED** [review]
:+1:

**Comment by ibc** [comment]
There is a bug but unclear whether it's introduced by this PR or not:

If the Producer has 3 encodings (so 3 simulcast spatial layers 0,1,2) and the encoding in the middle (encoding 1) has `active: false`, then when the consumer calls `setPreferredLayers({ spatial: 1 })` mediasoup selects layer 2 instead of 0.

CleanShot 2024-10-18 at 17 51 33

Nah, confirmed that it also happens in v3 branch.

**Comment by ggarber** [comment]
With this change can it happen that we start forwarding spatial layer 2 before having a SR for that layer and then we switch to other layer when we receive a SR for that new layer?

I that case how can mediasoup maintain continuous timestamps if it doesn't have the SR of layer 2?

**Comment by ibc** [comment]
Nothing has changed regarding that. If no SR has been received for any spatial layer (simulcast stream) mediasoup selects the first available stream. If layer SR arrive for one or more layers then mediasoup could of course switch to them if there is SR for that layer and if that spatial layer is equal or lower than preferred spatial layer.

HOWEVER while testing this PR locally I've seen and reported a bug that was there since ever. Check the most recent created issue in GH.

**Pull request merged**
