### PR TITLE
[mediasoup-worker] Require C++17, Meson >= 1.1.0 and update subprojects

### LINKED ISSUE #1080: old version of abseil causes error during installation
### Your environment

- Operating system: archlinux 6.3.1-arch1-1 (64-bit)
- Node version: v19.9.0
- npm version: 8.19.2
- gcc/clang version: gcc version 13.1.1 20230429 (GCC)
- mediasoup version: 3.11.24
- mediasoup-client version: 3.6.84

### Issue description

When i try to install mediasoup with "npm i mediasoup" i get the following error.
Error log: 
[2023-05-13T09_25_32_203Z-debug-0.log](https://github.com/versatica/mediasoup/files/11469860/2023-05-13T09_25_32_203Z-debug-0.log)

I asked for help in the mediasoup forum https://mediasoup.discourse.group/t/need-help-installing-mediasoup/5222 and im told the problem is "Since mediasoup does not compile with gcc-13, because it uses outdated version of abseil, it’s the problem of mediasoup"

i can install mediasoup-client package without any problem. Bu cant install the mediasoup

### PR DESCRIPTION
**Pull request by ibc**
Fixes #1080

- We could just require C++14 but let's move to C++17.
- Also update required meson version to 1.1.0.

**TODO:** Once published, update installation requirements in website.

### CODE REVIEW

**Comment by ibc** [comment]
@nazar-pc which version of Meson should I set in `meson.build`? **1.1.0**??? https://pypi.org/project/meson/

**Comment by nazar-pc** [comment]
Latest Meson release is 1.1.0 and was released weeks ago (we still use pre-1.0), I suggest using `>=1.1.0` in this case unless we have any CI errors. Note that this will also increase Python requirements from 3.6 to 3.7.

**Comment by ibc** [comment]
Ok. Wondering if we could also update ninja version. Remember that we limit it to 1.10.2.4 in `Makefile` due to this:

```make
# Let's use a specific version of ninja to avoid buggy version 1.11.1:
# https://mediasoup.discourse.group/t/partly-solved-could-not-detect-ninja-v1-8-2-or-newer/
# https://github.com/ninja-build/ninja/issues/2211
# https://github.com/ninja-build/ninja/issues/2212
NINJA_VERSION ?= 1.10.2.4
```

**Comment by nazar-pc** [comment]
I don't think we need to limit either. Meson requirements are 1.8.2+, so we are good either way, but you can update to newer version if there is one.

**Review by jmillan — APPROVED** [review]

**Comment by ibc** [comment]
> Ok. Wondering if we could also update ninja version. Remember that we limit it to 1.10.2.4 in `Makefile` due to this:
> 
> ```makefile
> # Let's use a specific version of ninja to avoid buggy version 1.11.1:
> # https://mediasoup.discourse.group/t/partly-solved-could-not-detect-ninja-v1-8-2-or-newer/
> # https://github.com/ninja-build/ninja/issues/2211
> # https://github.com/ninja-build/ninja/issues/2212
> NINJA_VERSION ?= 1.10.2.4
> ```

I cannot figure it out. Question made here: https://github.com/scikit-build/ninja-python-distributions/issues/157#issuecomment-1550017775

**Comment by ibc** [comment]
OMG https://github.com/versatica/mediasoup/actions/runs/4994428077/jobs/8944973803?pr=1081

**Comment by ibc** [comment]
@nazar-pc I cannot run `cargo test` locally and it miserably fails with `meson.build:1:0: ERROR: Meson version is 0.61.5 but project requires >= 1.1.0`...

```
cargo test
   Compiling mediasoup-sys v0.5.4 (/Users/ibc/src/v3-mediasoup/worker)
error: failed to run custom build command for `mediasoup-sys v0.5.4 (/Users/ibc/src/v3-mediasoup/worker)`

Caused by:
  process didn't exit successfully: `/Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-ecce322bae1686d4/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib
  cargo:rustc-link-lib=dylib=c++
  cargo:rustc-link-lib=dylib=c++abi
  /Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out/out/pip/bin/meson setup \
  		--prefix /Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out \
  		--bindir '' \
  		--libdir '' \
  		--buildtype debug \
  		-Db_pie=true \
  		-Db_staticpic=true \
  		--reconfigure \
  		"" \
  		/Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out/build || \
  		/Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out/out/pip/bin/meson setup \
  			--prefix /Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out \
  			--bindir '' \
  			--libdir '' \
  			--buildtype debug \
  			-Db_pie=true \
  			-Db_staticpic=true \
  			"" \
  			/Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out/build
  The Meson build system
  Version: 0.61.5
  Source dir: /Users/ibc/src/v3-mediasoup/worker
  Build dir: /Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out/build
  Build type: native build

  meson.build:1:0: ERROR: Meson version is 0.61.5 but project requires >= 1.1.0

  A full log can be found at /Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out/build/meson-logs/meson-log.txt
  Directory already configured.

  Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
  If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
  to force Meson to regenerate.

  If build failures persist, run "meson setup --wipe" to rebuild from scratch
  using the same options as passed when configuring the build.
  To change option values, run "meson configure" instead.
  /Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out/out/pip/bin/meson compile -C /Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out/build -j 16 libmediasoup-worker
  ninja: Entering directory `/Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out/build'
```

**Comment by nazar-pc** [comment]
Try deleting `/Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out`, looks like you have Meson installed there from the older runs

**Comment by ibc** [comment]
> Try deleting `/Users/ibc/src/v3-mediasoup/target/debug/build/mediasoup-sys-f797145957fa5d57/out`, looks like you have Meson installed there from the older runs

Thanks. But shouldn't some of the `make clean-xxx` we have do that?

**Comment by nazar-pc** [comment]
I don't think we have a separate cleanup method for that. It is cleaned up by default at the end actually, but not when error happens 😕

**Comment by ibc** [comment]
So `cargo` commands work in my computer. But CI fails with this error:

https://github.com/versatica/mediasoup/actions/runs/4994428077/jobs/8944973803?pr=1081

```
 /usr/bin/ld: /home/runner/work/mediasoup/mediasoup/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/libmediasoup-worker.a(absl_strings_internal_cord_rep_crc.cc.o): in function `absl::lts_20230125::cord_internal::CordRepCrc::CordRepCrc()':
```

Note that it's about `mediasoup/target/debug/build`. Why is it generating debug release? I cannot ssh the CI server and manually delete that folder...

**Comment by nazar-pc** [comment]
Maybe it succeeds on macOS, but requires something on Linux, I will look into it later.

> Why is it generating debug release?

Why wouldn't it? Debug is the default for testing and similar purposes. We are caching some stuff in CI, but not `target`.

**Comment by ibc** [comment]
> > Why is it generating debug release?
> 
> Why wouldn't it? Debug is the default for testing and similar purposes. We are caching some stuff in CI, but not `target`.

True, ignore it please.

**Comment by ibc** [comment]
@jmillan it fails to build on our server (jsut run `make` on `/tmp/mediasoup/worker`) :(
This is a fresh clone of mediasoup using the branch in this PR:

```
Found ninja-1.10.2.git.kitware.jobserver-1 at /tmp/kk/mediasoup/worker/out/pip/bin/ninja
/tmp/kk/mediasoup/worker/out/pip/bin/meson compile -C /tmp/kk/mediasoup/worker/out/Release/build -j 2 mediasoup-worker
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /tmp/kk/mediasoup/worker/out/pip/bin/ninja -C /tmp/kk/mediasoup/worker/out/Release/build -j 2 mediasoup-worker
ninja: Entering directory `/tmp/kk/mediasoup/worker/out/Release/build'
[1061/1333] Compiling C++ object subprojects/abseil-cpp-20230125.1/libabsl_base.a.p/absl_base_internal_cycleclock.cc.o
FAILED: subprojects/abseil-cpp-20230125.1/libabsl_base.a.p/absl_base_internal_cycleclock.cc.o
c++ -Isubprojects/abseil-cpp-20230125.1/libabsl_base.a.p -Isubprojects/abseil-cpp-20230125.1 -I../../../subprojects/abseil-cpp-20230125.1 -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -std=c++14 -O3 -Wno-sign-compare -fPIC -pthread -MD -MQ subprojects/abseil-cpp-20230125.1/libabsl_base.a.p/absl_base_internal_cycleclock.cc.o -MF subprojects/abseil-cpp-20230125.1/libabsl_base.a.p/absl_base_internal_cycleclock.cc.o.d -o subprojects/abseil-cpp-20230125.1/libabsl_base.a.p/absl_base_internal_cycleclock.cc.o -c ../../../subprojects/abseil-cpp-20230125.1/absl/base/internal/cycleclock.cc
In file included from ../../../subprojects/abseil-cpp-20230125.1/absl/base/config.h:86:0,
                 from ../../../subprojects/abseil-cpp-20230125.1/absl/base/attributes.h:37,
                 from ../../../subprojects/abseil-cpp-20230125.1/absl/base/internal/cycleclock.h:48,
                 from ../../../subprojects/abseil-cpp-20230125.1/absl/base/internal/cycleclock.cc:23:
../../../subprojects/abseil-cpp-20230125.1/absl/base/policy_checks.h:57:2: error: #error "This package requires GCC 7 or higher."
 #error "This package requires GCC 7 or higher."
  ^~~~~
[1062/1333] Compiling C++ object subprojects/abseil-cpp-20230125.1/libabsl_base.a.p/absl_base_internal_low_level_alloc.cc.o
FAILED: subprojects/abseil-cpp-20230125.1/libabsl_base.a.p/absl_base_internal_low_level_alloc.cc.o
c++ -Isubprojects/abseil-cpp-20230125.1/libabsl_base.a.p -Isubprojects/abseil-cpp-20230125.1 -I../../../subprojects/abseil-cpp-20230125.1 -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -std=c++14 -O3 -Wno-sign-compare -fPIC -pthread -MD -MQ subprojects/abseil-cpp-20230125.1/libabsl_base.a.p/absl_base_internal_low_level_alloc.cc.o -MF subprojects/abseil-cpp-20230125.1/libabsl_base.a.p/absl_base_internal_low_level_alloc.cc.o.d -o subprojects/abseil-cpp-20230125.1/libabsl_base.a.p/absl_base_internal_low_level_alloc.cc.o -c ../../../subprojects/abseil-cpp-20230125.1/absl/base/internal/low_level_alloc.cc
In file included from ../../../subprojects/abseil-cpp-20230125.1/absl/base/config.h:86:0,
                 from ../../../subprojects/abseil-cpp-20230125.1/absl/base/attributes.h:37,
                 from ../../../subprojects/abseil-cpp-20230125.1/absl/base/internal/low_level_alloc.h:31,
                 from ../../../subprojects/abseil-cpp-20230125.1/absl/base/internal/low_level_alloc.cc:20:
../../../subprojects/abseil-cpp-20230125.1/absl/base/policy_checks.h:57:2: error: #error "This package requires GCC 7 or higher."
 #error "This package requires GCC 7 or higher."
  ^~~~~
ninja: build stopped: subcommand failed.
Makefile:199: recipe for target 'mediasoup-worker' failed
make: *** [mediasoup-worker] Error 1
```

So... `#error "This package requires GCC 7 or higher."`

Amazing :(

**Comment by ibc** [comment]
@nazar-pc @jmillan as said here we cannot update Meson version yet in our Makefile:

https://github.com/scikit-build/ninja-python-distributions/issues/157#issuecomment-1550187704

**Comment by ibc** [comment]
> it fails to build on our server

This has been fixed in our server by upgrading to gcc 7 (it was 6), done by @jmillan. We are good.

**Comment by jmillan** [comment]
> This has been fixed in our server by upgrading to gcc 7 (it was 6), done by @nazar-pc. We are good.

Hehehe

**Comment by ibc** [comment]
> Hehehe

GH mobile sucks. Fixed.

**Comment by ibc** [comment]
@nazar-pc "good news" is that I can reproduce the Rust+Linux issue in our Debian 11 server by just running `cargo test` in main mediasoup folder:

<details>

```
$ cargo test
   Compiling mediasoup v0.11.4 (/home/deploy/src/mediasoup-git-repo/rust)
   Compiling mediasoup-sys v0.5.4 (/home/deploy/src/mediasoup-git-repo/worker)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcNe3S8z/symbols.o" "/home/deploy/src/mediasoup-git-repo/target/debug/deps/mediasoup_sys-afbcf8e1bac9f50a.15z88gheo1uq3l69.rcgu.o" "/home/deploy/src/mediasoup-git-repo/target/debug/deps/mediasoup_sys-afbcf8e1bac9f50a.1qemnk22vx794odi.rcgu.o" "/home/deploy/src/mediasoup-git-repo/target/debug/deps/mediasoup_sys-afbcf8e1bac9f50a.237r032jcn08csy2.rcgu.o" "/home/deploy/src/mediasoup-git-repo/target/debug/deps/mediasoup_sys-afbcf8e1bac9f50a.438yiyscz2ua5t5g.rcgu.o" "/home/deploy/src/mediasoup-git-repo/target/debug/deps/mediasoup_sys-afbcf8e1bac9f50a.4yeaguvuey6xpn9n.rcgu.o" "/home/deploy/src/mediasoup-git-repo/target/debug/deps/mediasoup_sys-afbcf8e1bac9f50a.2u30290lzyugjtd3.rcgu.o" "-Wl,--as-needed" "-L" "/home/deploy/src/mediasoup-git-repo/target/debug/deps" "-L" "/usr/lib/gcc/x86_64-linux-gnu/10/" "-L" "/home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out" "-L" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lstdc++" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lmediasoup-worker" "-Wl,--no-whole-archive" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-aa7b246d7b35480c.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-6095bf995c453e89.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-ae66bd5269d6d83c.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-6352d71bf8e7bd57.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-2a15b3cd0948397b.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-8f251cec381c549e.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-e8062a7445a64946.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-431dd9a65eafb1c5.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-5d5a85338b125cfb.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-3cf84ad460df483a.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-5a049915d61fbb5d.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-aabc21fad3549c98.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-dac6992ac677a0cb.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-3cd49acf880d0306.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-6c93f515800d4657.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-8a30445cf40d74de.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-47cbfc4f5b0f6f87.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-0b6ce813aa5d1704.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-f0ffbd64420a69ad.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-60668236929c1cf5.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2fb2d4481260f706.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-c888e061ea504c93.rlib" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-93189d615c3f2d6a.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/deploy/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/deploy/src/mediasoup-git-repo/target/debug/deps/mediasoup_sys-afbcf8e1bac9f50a" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/libmediasoup-worker.a(absl_strings_cord.cc.o): in function `absl::lts_20230125::Cord::SetCrcCordState(absl::lts_20230125::crc_internal::CrcCordState)':
          /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:860: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::CrcCordState(absl::lts_20230125::crc_internal::CrcCordState&&)'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:860: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::~CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:864: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::CrcCordState(absl::lts_20230125::crc_internal::CrcCordState&&)'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:864: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::~CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:868: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::CrcCordState(absl::lts_20230125::crc_internal::CrcCordState&&)'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:868: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::~CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:860: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::~CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:864: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::~CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:868: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::~CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/libmediasoup-worker.a(absl_strings_cord.cc.o): in function `absl::lts_20230125::Cord::SetExpectedChecksum(unsigned int)':
          /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:875: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:878: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::CrcCordState(absl::lts_20230125::crc_internal::CrcCordState&&)'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:878: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::~CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:875: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::~CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:878: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::~CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:875: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::~CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/libmediasoup-worker.a(absl_strings_cord.cc.o): in function `absl::lts_20230125::Cord::ExpectedChecksum() const':
          /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:893: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::Checksum() const'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/libmediasoup-worker.a(absl_strings_cord.cc.o): in function `absl::lts_20230125::DumpNode(absl::lts_20230125::cord_internal::CordRep*, bool, std::ostream*, int)':
          /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/cord.cc:1273: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::Checksum() const'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/libmediasoup-worker.a(absl_strings_cord.cc.o): in function `absl::lts_20230125::cord_internal::CordRepCrc::~CordRepCrc()':
          /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/internal/cord_rep_crc.h:36: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::~CrcCordState()'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/libmediasoup-worker.a(absl_strings_internal_cord_rep_crc.cc.o): in function `absl::lts_20230125::cord_internal::CordRepCrc::New(absl::lts_20230125::cord_internal::CordRep*, absl::lts_20230125::crc_internal::CrcCordState)':
          /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/internal/cord_rep_crc.cc:31: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::operator=(absl::lts_20230125::crc_internal::CrcCordState&&)'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/internal/cord_rep_crc.cc:43: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::operator=(absl::lts_20230125::crc_internal::CrcCordState&&)'
          /usr/bin/ld: /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/libmediasoup-worker.a(absl_strings_internal_cord_rep_crc.cc.o): in function `absl::lts_20230125::cord_internal::CordRepCrc::CordRepCrc()':
          /home/deploy/src/mediasoup-git-repo/target/debug/build/mediasoup-sys-7ed5151ea7b1f08b/out/build/../../../../../../worker/subprojects/abseil-cpp-20230125.1/absl/strings/internal/cord_rep_crc.h:36: undefined reference to `absl::lts_20230125::crc_internal::CrcCordState::CrcCordState()'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `mediasoup-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
```

</details>

I don't really understand what is going on. `make`  and `make test` Makefile tasks do work. How can the above failure happen when running `cargo`? It's obviously a linking issue but no idea which one.

**Comment by ibc** [comment]
Maybe this: https://stackoverflow.com/questions/69866575/why-cant-linker-find-absl-references

A guy having a similar problem with abseil-cpp when building his project using C++17.

**Comment by nazar-pc** [comment]
Does using C++14 solve the problem for now? I think that would be the easiest to do for now, we don't have to use C++17 right now.

**Comment by ibc** [comment]
Protobuf also having similar problems: https://github.com/protocolbuffers/protobuf/issues/12292

**Comment by ibc** [comment]
> undefined reference to `absl::lts_20230125::crc_internal::

Trying to build with C++14 right now. For whatever reason it takes forever to build when running `cargo test`.

**Comment by nazar-pc** [comment]
> For whatever reason it takes forever to build when running cargo test.

It doesn't cache anything between builds, so needs cores to build faster.

**Comment by ibc** [comment]
Same problem with C++14. I suspect it's not related to C++ version but to the updated version of abseil-cpp.

**Comment by ibc** [comment]
And I cannot try with C++11 (as in v3) because updated version of abseil-cpp requires C++14 or greater.

**Comment by nazar-pc** [comment]
As mentioned in https://github.com/mesonbuild/wrapdb/pull/932 latest release is somewhat broken. When I was doing upgrades, I was checking the diff of CMakeFiles between releases, something might have happened that was not accounted for. There is WIP https://github.com/mesonbuild/wrapdb/pull/996 that might address it eventually, I have downgraded abseil-cpp to the previous release for now. Still requires C++14 and should be new enough to resolve original issue.

Feel free to investigate what happened to abseil-cpp upstream, I'm not in the mood to dig into it right now.

**Comment by ibc** [comment]
Are you 100% sure that abseil-cpp-20220623.0 also contains the fix? See https://github.com/versatica/mediasoup/issues/1080#issuecomment-1549942805

**Comment by nazar-pc** [comment]
No, not 100%. @estnml would you mind to try this branch and confirm or deny?

GitHub Actions doesn't have GCC 13 yet either.

**Comment by ibc** [comment]
> As mentioned in [mesonbuild/wrapdb#932](https://github.com/mesonbuild/wrapdb/pull/932) latest release is somewhat broken. When I was doing upgrades, I was checking the diff of CMakeFiles between releases, something might have happened that was not accounted for. There is WIP [mesonbuild/wrapdb#996](https://github.com/mesonbuild/wrapdb/pull/996) that might address it eventually

Just in case, I was replied this (but I have no idea what it means):

https://github.com/protocolbuffers/protobuf/issues/12292#issuecomment-1551569419

CleanShot-2023-05-17-at-18 00 04@2x

So options are:

1. We can wait for new version of abseil-cpp in Meson Wrapdb (indeed there is a known linking issue in the current latest one).
2. Or we can use previous version assuming that @estnml confirms that this branch works with gcc 13.

**Comment by nazar-pc** [comment]
There is also option 3: fix it ourselves instead of waiting :wink:

**Comment by ibc** [comment]
> There is also option 3: fix it ourselves instead of waiting 😉

Fix where?

**Comment by nazar-pc** [comment]
Wherever the issue is. Likely in Meson wrap, but investigation is probably necessary.

**Comment by estnml** [comment]
Hi @ibc @nazar-pc , here is what i did:
1. clone the mediasoup repo
2. change branch to "require-c++17-and-update-subprojects"
3. run "npm install" on the folder.

The command ran successfully.

gcc --version: gcc (GCC) 13.1.1 20230429

**Comment by nazar-pc** [comment]
Should be good enough for now then, thanks for verifying!

**Comment by estnml** [comment]
I'm glad I could help, and thanks for this beautiful project.

**Comment by ibc** [comment]
Thanks a lot! Merging. Will release tomorrow.

**Comment by ibc** [comment]
mediasoup-node 3.11.25 released and website updated (required Python >= 3.7 and C++17).

**Comment by jmillan** [comment]
Beautiful, thanks guys!

**Pull request merged**
