### PR TITLE
Worker: Fix possible double free when ICE consent check fails

### LINKED ISSUE #1392: Mediasoup worker died, exiting in 2 seconds...
### System Information and Environment:

- **Operating System:** Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-105-generic x86_64)
- **Mediasoup Version:** 3.14.5
- **Mediasoup Client Version:** 3.7.7
- **Compiler:** gcc/g++/c++ 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
- **Node.js Version:** v18.17.1
- **Npm Version**: 10.7.0
- **Python Version:** 3.10.12
- **Docker**: 24.0.5, build 24.0.5-0ubuntu1~22.04.1
- **Docker-compose**: v2.27.0

For reference: [mediasoup.discourse.group](https://mediasoup.discourse.group/t/mediasoup-worker-died-exiting-in-2-seconds/6035/9)

### Issue Description:

Since upgrading to Mediasoup version `3.14.5`, our system has encountered frequent instances of Mediasoup workers terminating unexpectedly. This behavior is indicated by the message `Mediasoup worker died, exiting in 2 seconds...`.

### Troubleshooting Steps:

Following the [documentation](https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump), we managed obtained a core dump of the worker, which will be provided as an attachment for further analysis.

</details>

<details>
<summary>(gdb) bt</summary>

<br/>

```bash
(gdb) bt
#0  0x000055604c64eb58 in RTC::TransportTuple::GetProtocol (this=0x556518627283) at ../../../include/RTC/TransportTuple.hpp:92
#1  0x000055604c766313 in RTC::WebRtcTransport::OnIceServerTupleRemoved (this=0x55604e65a2b0, tuple=0x556518627283)
    at ../../../src/RTC/WebRtcTransport.cpp:1183
#2  0x000055604c64ef97 in RTC::IceServer::OnTimer (this=0x55604e615820, timer=0x55604e67fa90) at ../../../src/RTC/IceServer.cpp:935
#3  0x000055604c5ff52e in TimerHandle::OnUvTimer (this=0x55604e67fa90) at ../../../src/handles/TimerHandle.cpp:162
#4  0x000055604c5fe87b in onTimer (handle=0x55604e692230) at ../../../src/handles/TimerHandle.cpp:13
#5  0x000055604cb49005 in uv__run_timers (loop=0x55604e53bff0) at ../../../subprojects/libuv-v1.48.0/src/timer.c:193
#6  0x000055604cb4ec72 in uv_run (loop=0x55604e53bff0, mode=UV_RUN_DEFAULT) at ../../../subprojects/libuv-v1.48.0/src/unix/core.c:466
#7  0x000055604c5cda83 in DepLibUV::RunLoop () at ../../../src/DepLibUV.cpp:98
#8  0x000055604c5e06ed in Worker::Worker (this=0x7fff8c7dd100, channel=0x55604e53c5d0) at ../../../src/Worker.cpp:56
#9  0x000055604c5c3414 in mediasoup_worker_run (argc=16, argv=0x7fff8c7dd348, version=0x7fff8c7dd200 "3.14.5", consumerChannelFd=3, producerChannelFd=4,
    channelReadFn=0x0, channelReadCtx=0x0, channelWriteFn=0x0, channelWriteCtx=0x0) at ../../../src/lib.cpp:142
#10 0x000055604c80ed5f in main (argc=16, argv=0x7fff8c7dd348) at ../../../src/main.cpp:25
```

</details>

</details>

<details>
<summary>(gdb) bt full</summary>

<br/>

```bash
#0  0x000055604c64eb58 in RTC::TransportTuple::GetProtocol (this=0x556518627283) at ../../../include/RTC/TransportTuple.hpp:92
No locals.
#1  0x000055604c766313 in RTC::WebRtcTransport::OnIceServerTupleRemoved (this=0x55604e65a2b0, tuple=0x556518627283)
    at ../../../src/RTC/WebRtcTransport.cpp:1183
No locals.
#2  0x000055604c64ef97 in RTC::IceServer::OnTimer (this=0x55604e615820, timer=0x55604e67fa90) at ../../../src/RTC/IceServer.cpp:935
        storedTuple = 0x556518627283
        it = <error reading variable: Cannot access memory at address 0x556518627283>
        __for_range = std::__cxx11::list = {[0] = {hash = 15945316816845144064, udpSocket = 0x55604e6c2030, udpRemoteAddr = 0x55604e6d24a0,
            tcpConnection = 0x0, localAnnouncedAddress = "", udpRemoteAddrStorage = {ss_family = 2,
              __ss_padding = "\335I%)\273\036", '\000' <repeats 111 times>, __ss_align = 0}, protocol = RTC::TransportTuple::Protocol::UDP}}
        __for_begin = <error reading variable: Cannot access memory at address 0x556518627273>
        __for_end = {hash = 1, udpSocket = 0x55604e6d2460, udpRemoteAddr = 0x55604e67fa90, tcpConnection = 0x0, localAnnouncedAddress = <error: Cannot access memory at address 0xe0>, udpRemoteAddrStorage = {ss_family = 1, __ss_padding = "\000\000\000\000\000\000xt\000\000\000\000\000\000\000\004\000\000\000\000\000\000\340YaN`U\000\000\003\000\000\000\000\000\000\000y\000\000\000\000\000\000\000", '\377' <repeats 16 times>, "\003\000\000\000\002\000\000\000\001", '\000' <repeats 31 times>, "a\000\000\000\000\000\000\000\260\326^N`U\000", __ss_align = 0}, protocol = (unknown: 0x80)}
        __FUNCTION__ = "OnTimer"
#3  0x000055604c5ff52e in TimerHandle::OnUvTimer (this=0x55604e67fa90) at ../../../src/handles/TimerHandle.cpp:162
No locals.
#4  0x000055604c5fe87b in onTimer (handle=0x55604e692230) at ../../../src/handles/TimerHandle.cpp:13
No locals.
#5  0x000055604cb49005 in uv__run_timers (loop=0x55604e53bff0) at ../../../subprojects/libuv-v1.48.0/src/timer.c:193
        heap_node = 0x55604e5fec88
        handle = 0x55604e692230
        queue_node = 0x55604e692298
        ready_queue = {next = 0x55604e629318, prev = 0x55604e721bd8}
#6  0x000055604cb4ec72 in uv_run (loop=0x55604e53bff0, mode=UV_RUN_DEFAULT) at ../../../subprojects/libuv-v1.48.0/src/unix/core.c:466
        timeout = 1
        r = 0
        can_sleep = 1
#7  0x000055604c5cda83 in DepLibUV::RunLoop () at ../../../src/DepLibUV.cpp:98
        __FUNCTION__ = "RunLoop"
        ret = 21856
#8  0x000055604c5e06ed in Worker::Worker (this=0x7fff8c7dd100, channel=0x55604e53c5d0) at ../../../src/Worker.cpp:56
--Type <RET> for more, q to quit, c to continue without paging--
No locals.
#9  0x000055604c5c3414 in mediasoup_worker_run (argc=16, argv=0x7fff8c7dd348, version=0x7fff8c7dd200 "3.14.5", consumerChannelFd=3, producerChannelFd=4, channelReadFn=0x0, channelReadCtx=0x0, channelWriteFn=0x0, channelWriteCtx=0x0) at ../../../src/lib.cpp:142
        worker = {<Channel::ChannelSocket::Listener> = {<Channel::ChannelSocket::RequestHandler> = {_vptr.RequestHandler = 0x55604cf6bb10 <vtable for Worker+16>}, <Channel::ChannelSocket::NotificationHandler> = {
              _vptr.NotificationHandler = 0x55604cf6bb58 <vtable for Worker+88>}, <No data fields>}, <SignalHandle::Listener> = {_vptr.Listener = 0x55604cf6bb80 <vtable for Worker+128>}, <RTC::Router::Listener> = {
            _vptr.Listener = 0x55604cf6bba8 <vtable for Worker+168>}, channel = 0x55604e53c5d0, signalHandle = 0x55604e5b3920, shared = 0x55604e5b2be0,
          mapWebRtcServers = {<absl::lts_20230802::container_internal::raw_hash_map<absl::lts_20230802::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, RTC::WebRtcServer*>, absl::lts_20230802::container_internal::StringHash, absl::lts_20230802::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::WebRtcServer*> > >> = {<absl::lts_20230802::container_internal::raw_hash_set<absl::lts_20230802::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, RTC::WebRtcServer*>, absl::lts_20230802::container_internal::StringHash, absl::lts_20230802::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::WebRtcServer*> > >> = {
                settings_ = {<absl::lts_20230802::container_internal::internal_compressed_tuple::CompressedTupleImpl<absl::lts_20230802::container_internal::CompressedTuple<absl::lts_20230802::container_internal::CommonFields, absl::lts_20230802::container_internal::StringHash, absl::lts_20230802::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::WebRtcServer*> > >, absl::lts_20230802::integer_sequence<unsigned long, 0, 1, 2, 3>, true>> = {<absl::lts_20230802::container_internal::internal_compressed_tuple::uses_inheritance> = {<No data fields>}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<absl::lts_20230802::container_internal::CommonFields, 0, false>> = {
                      value = {<absl::lts_20230802::container_internal::CommonFieldsGenerationInfoDisabled> = {<No data fields>}, control_ = 0x55604cd31d40 <absl::lts_20230802::container_internal::kEmptyGroup+16>, slots_ = 0x0, capacity_ = 0,
                        compressed_tuple_ = {<absl::lts_20230802::container_internal::internal_compressed_tuple::CompressedTupleImpl<absl::lts_20230802::container_internal::CompressedTuple<unsigned long, absl::lts_20230802::container_internal::HashtablezInfoHandle>, absl::lts_20230802::integer_sequence<unsigned long, 0, 1>, true>> = {<absl::lts_20230802::container_internal::internal_compressed_tuple::uses_inheritance> = {<No data fields>}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<unsigned long, 0, false>> = {
                              value = 0}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<absl::lts_20230802::container_internal::HashtablezInfoHandle, 1, true>> = {<absl::lts_20230802::container_internal::HashtablezInfoHandle> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<absl::lts_20230802::container_internal::StringHash, 1, true>> = {<absl::lts_20230802::container_internal::StringHash> = {<No data fields>}, <No data fields>}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<absl::lts_20230802::container_internal::StringEq, 2, true>> = {<absl::lts_20230802::container_internal::StringEq> = {<No data fields>}, <No data fields>}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::WebRtcServer*> >, 3, true>> = {<std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::WebRtcServer*> >> = {<__gnu_cxx::new_allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::WebRtcServer*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}, <No data fields>},
          mapRouters = {<absl::lts_20230802::container_internal::raw_hash_map<absl::lts_20230802::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, RTC::Router*>, absl::lts_20230802::container_internal::StringHash, absl::lts_20230802::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::Router*> > >> = {<absl::lts_20230802::container_internal::raw_hash_set<absl::lts_20230802::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, RTC::Router*>, absl::lts_20230802::container_internal::StringHash, absl::lts_20230802::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::Router*> > >> = {
                settings_ = {<absl::lts_20230802::container_internal::internal_compressed_tuple::CompressedTupleImpl<absl::lts_20230802::container_internal::CompressedTuple<absl::lts_20230802::container_internal::CommonFields, absl::lts_20230802::container_internal::StringHash, absl::lts_20230802::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::Router*> > >, absl::lts_20230802::integer_sequence<unsigned long, 0, 1, 2, 3>, true>> = {<absl::lts_20230802::container_internal::internal_compressed_tuple::uses_inheritance> = {<No data fields>}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<absl::lts_20230802::container_internal::CommonFields, 0, false>> = {
                      value = {<absl::lts_20230802::container_internal::CommonFieldsGenerationInfoDisabled> = {<No data fields>}, control_ = 0x55604e6bef58, slots_ = 0x55604e6bef70, capacity_ = 3,
                        compressed_tuple_ = {<absl::lts_20230802::container_internal::internal_compressed_tuple::CompressedTupleImpl<absl::lts_20230802::container_internal::CompressedTuple<unsigned long, absl::lts_20230802::container_internal::HashtablezInfoHandle>, absl::lts_20230802::integer_sequence<unsigned long, 0, 1>, true>> = {<absl::lts_20230802::container_internal::internal_compressed_tuple::uses_inheritance> = {<No data fields>}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<unsigned long, 0, false>> = {
                              value = 2}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<absl::lts_20230802::container_internal::HashtablezInfoHandle, 1, true>> = {<absl::lts_20230802::container_internal::HashtablezInfoHandle> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<absl::lts_20230802::container_internal::StringHash, 1, true>> = {<absl::lts_20230802::container_internal::StringHash> = {<No data fields>}, <No data fields>}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<absl::lts_20230802::container_internal::StringEq, 2, true>> = {<absl::lts_20230802::container_internal::StringEq> = {<No data fields>}, <No data fields>}, <absl::lts_20230802::container_internal::internal_compressed_tuple::Storage<std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::Router*> >, 3, true>> = {<std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::Router*> >> = {<__gnu_cxx::new_allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, RTC::Router*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}, <No data fields>}, closed = false}
        channel = std::unique_ptr<Channel::ChannelSocket> = {get() = 0x55604e53c5d0}
        __FUNCTION__ = "mediasoup_worker_run"
#10 0x000055604c80ed5f in main (argc=16, argv=0x7fff8c7dd348) at ../../../src/main.cpp:25
        __FUNCTION__ = "main"
        version = "3.14.5"
        statusCode = 0
```

</details>

### PR DESCRIPTION
**Pull request by ibc**
Fixes #1392

### CODE REVIEW

**Comment by ibc** [comment]
@miroslavpejic85, I've not been able to reproduce the crash even by forcing things that IMHO should trigger the crash. Anyway, I think that this PR is gonna fix it.

Is it possible that you try this branch and confirm whether it solves the crash or not?

**Review by jmillan — APPROVED** [review]

**Comment by ibc** [comment]
This flow is super complex but it's what it is:

When calling `webRtcServer.close()` having active TCP connections:

1. `~WebRtcServer` iterates all its `WebRtcTransports` and calls `webRtcTransport->ListenServerClosed()``.

2. `Transport::ListenServerClosed()` calls `this->listener->OnTransportListenServerClosed()`.

3. So `Router` deletes transport.

4. `~WebRtcTransport` deletes `IceServer`.

5. `~IceServer` iterates tuples and calls `this->listener->OnIceServerTupleRemoved(tuple)`.

6. So `WebRtcTransport` calls `tuple->CloseTcpConnection()`.

7. `TransportTuple::CloseTcpConnection()` calls `tcpConnection->TriggerClose()`.

8. So `TcpConnectionHandle` calls `this->listener->OnTcpConnectionClosed()`.

9. So `TcpServerHandle` calls `UserOnTcpConnectionClosed()` which calls `this->listener->OnRtcTcpConnectionClosed()` **[A]**, and then deletes the `TcpConnectionHandle`.

Problem is **[A]** since it ends calling `iceServer->RemoveTuple()` which calls `listener->OnIceServerTupleRemoved()` again with same tuple.

**Comment by miroslavpejic85** [comment]
> Is it possible that you try this branch and confirm whether it solves the crash or not?

Sure, I need to reconstruct the worker on this branch and give it a try right?

```bash
cd worker; MEDIASOUP_BUILDTYPE='Debug' make
```

**Comment by ibc** [comment]
Yes. Or just add a git url pointing to this branch as mediasoup dependency in the package.json of your server app and run "npm install mediasoup".

**Comment by miroslavpejic85** [comment]
> When calling `webRtcServer.close()` having active TCP connections:

Note: The crash occurs despite not utilizing the `WebRtcServer`, but rather relying on the default [WebRtcTransportOption](https://github.com/versatica/mediasoup-demo/blob/v3/server/config.example.js#L141) for the transports.

**Comment by ibc** [comment]
The fix in this PR is not related to WebRtcServer so it may be valid (assuming in doesn't crash anymore for you once you try the branch).

**Comment by miroslavpejic85** [comment]
Great, then I'll try the fix and keep you updated.

**Comment by snnz** [comment]
> 5\. `~IceServer` iterates tuples and calls `this->listener->OnIceServerTupleRemoved(tuple)`.

I think this can happen wherever `OnIceServerTupleRemoved` is called with a tuple containing TCP connection that is not closed yet.
In IceServer::AddTuple, when the `tuples` size exceeds `MaxTuples`:
```
this->listener->OnIceServerTupleRemoved(this, removedTuple);
this->tuples.erase(std::next(it).base());
```
What the iterator will point to? This will either crash, or destroy some extra tuple.

In `IceServer::RemoveTuple` it will stop short of recursively calling itself, because at that moment the connection is already closed, but nevertheless, it'll dive in `webRtcTransportListener->OnWebRtcTransportTransportTupleRemoved`, `tuple->CloseTcpConnection` - rather unnecessary.
It's better to block reenter `IceServer::RemoveTuple` from any method that calls `OnIceServerTupleRemoved`, including `IceServer::RemoveTuple` itself.

**Comment by ibc** [comment]
> > 5. `~IceServer` iterates tuples and calls `this->listener->OnIceServerTupleRemoved(tuple)`.
> 
> I think this can happen wherever `OnIceServerTupleRemoved` is called with a tuple containing TCP connection that is not closed yet. In IceServer::AddTuple, when the `tuples` size exceeds `MaxTuples`:
> 
> ```
> this->listener->OnIceServerTupleRemoved(this, removedTuple);
> this->tuples.erase(std::next(it).base());
> ```
> 
> What the iterator will point to? This will either crash, or destroy some extra tuple.

It's indeed crashing but not sure why. This was done and tested long ago, not sure what has changed. I've just set `static constexpr size_t MaxTuples{ 1 };` in `IceServer.cpp`, connected a client with TCP and triggered a ICE restart (mediasoup demo):

```
  mediasoup:Channel request() [method:TRANSPORT_RESTART_ICE] +7s
  mediasoup:Channel request succeeded [method:TRANSPORT_RESTART_ICE, id:57] +0ms
  mediasoup:WARN:Channel [pid:35928] RTC::IceServer::AddTuple() | too too many tuples, removing the oldest non selected one +0ms
  mediasoup:ERROR:Worker (stderr) (ABORT) RTC::IceServer::AddTuple() | failed assertion `removedTuple': couldn't find any tuple to be removed +0ms
```

However I think it crashes because the code assumes that `MaxTuples` is > 1.

> What the iterator will point to? This will either crash, or destroy some extra tuple.

Why do you think it will crash? The comment above it clearly indicates what it does:

```c++
			// Notify the listener.
			this->listener->OnIceServerTupleRemoved(this, removedTuple);

			// Remove it from the list of tuples.
			// NOTE: Do it after notifying the listener since the listener may need to
			// use/read the tuple being removed so we cannot free it yet.
			// NOTE: This trick is needed since it is a reverse_iterator and
			// erase() requires a iterator, const_iterator or bidirectional_iterator.
			this->tuples.erase(std::next(it).base());
```


 
> In `IceServer::RemoveTuple` it will stop short of recursively calling itself, because at that moment the connection is already closed, but nevertheless, it'll dive in `webRtcTransportListener->OnWebRtcTransportTransportTupleRemoved`, `tuple->CloseTcpConnection` - rather unnecessary. It's better to block reenter `IceServer::RemoveTuple` from any method that calls `OnIceServerTupleRemoved`, including `IceServer::RemoveTuple` itself.

I also expected this to happen, but for whatever reason it doesn't (or I couldn't reproduce it). But I agree that it makes sense that we block reenter of `RemoveTuple()` while invoking the `listener->OnIceServerTupleRemoved()` callback. I'll do it soon.

**Comment by ibc** [comment]
@snnz I've done it in last commit, can you check?

**Comment by snnz** [comment]
> Why do you think it will crash?

Because `this->listener->OnIceServerTupleRemoved(this, removedTuple)` will, through all that chain, call `this->RemoveTuple(removedTuple)` , which will find and erase `removedTuple`.

> @snnz I've done it in last commit, can you check?

Everything is ok now, I believe this will fix the problem.

**Comment by ibc** [comment]
> In IceServer::RemoveTuple it will stop short of recursively calling itself, because at that moment the connection is already closed

While this PR fixes this I still don't understand why (before this PR) we didn't get an infinite loop. You say that it will stop recursively calling itself because the connection is closed, but we do not check if the connection is closed anywhere (if closed it should be deleted or being deleted). Well, now that I think about it I just removed that check in a recent related PR. Anyway I think everything is ok now.

**Comment by snnz** [comment]
> but we do not check if the connection is closed anywhere

But there is a check, in `TcpConnectionHandle::TriggerClose`:

```
void TcpConnectionHandle::TriggerClose()
{
	MS_TRACE();

	if (this->closed)
	{
		return;
	}

	InternalClose();

	this->listener->OnTcpConnectionClosed(this);
}
```

`InternalClose` sets `closed` flag, thus next time `TriggerClose` won't proceed and call `OnTcpConnectionClosed`.

**Comment by ibc** [comment]
True.

**Comment by ibc** [comment]
@miroslavpejic85 any ETA for you to test this branch? After the discussion above it's clear that these changes make sense and I'd like to release ASAP, but having your ok would be great.

**Comment by miroslavpejic85** [comment]
@ibc Everything seems to be running smoothly now, without any worker crashes since yesterday. You can go ahead and release it. Thank you!

**Comment by ibc** [comment]
> @ibc Everything seems to be running smoothly now, without any worker crashes since yesterday. You can go ahead and release it. Thank you!

Thanks a lot!

**Comment by miroslavpejic85** [comment]
> Thanks a lot!

You're welcome! And thank you for addressing the issue promptly ;)

**Pull request merged**
