### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by jmillan**
Extracted from `memory-optimizations` branch.

### CODE REVIEW

**Comment by jmillan** [comment]
mmm, CI failing for Rust.

**Comment by ibc** [comment]
Please no :(

**Review by ibc — COMMENTED** [review]
Why are we removing this? It's also in UDP and Unix socket

**Comment by jmillan** [comment]
> Please no :(

It's unused code. Is there any plan to use it?

**Comment by nazar-pc** [comment]
I fixed Rust in the other PR. It was caused by use of unstable crates in examples and lack of lock file in the repo

**Review by nazar-pc — APPROVED** [review]

**Comment by ibc** [comment]
> Why are we removing this? It's also in UDP and Unix socket 

What about this?

**Comment by nazar-pc** [comment]
> What about this?

In that place it is actually used

**Comment by ibc** [comment]
> > What about this?
> 
> 
> 
> In that place it is actually used

Sorry, what do you mean?

**Comment by nazar-pc** [comment]
I mean the code was probably copy pasted from UDP into TCP. In UDP those methods are functional, in TCP they are just dead code.

**Comment by ibc** [comment]
> I mean the code was probably copy pasted from UDP into TCP. In UDP those methods are functional, in TCP they are just dead code.

Are we really using the `std::string` arg based send method in UDP? I'm not aware of it.

**Comment by nazar-pc** [comment]
> Are we really using the std::string arg based send method in UDP? I'm not aware of it.

I mean whatever the method looks like there. The point is the code removed by this PR is not used anywhere.

**Review by ibc — APPROVED** [review]
Sorry, my fault. Indeed we never use these tcp methods since we always write two datas due to the framing mechanism of RTC TCP.

**Pull request merged**
