### PR TITLE
Add support for Opus NACK 

### PR DESCRIPTION
**Pull request by t-mullen**
Adds support for NACK packets and retransmissions when using Opus.
This makes a significant difference when packet loss is high. Here's some samples with 40% packet loss.
Before: https://voca.ro/1drKi1WrGBbL
After: https://voca.ro/1c5NmOL4D42u

Changes summary:
- Added an `ignoreNack` option to ConsumerOptions - this is the TX equivalent of the `codecOptions.opusNack` option in [my other PR,](https://github.com/versatica/mediasoup-client/pull/242).
- Added the `{ type: 'nack' }` RTP capability to Opus.

Depends on client PR: https://github.com/versatica/mediasoup-client/pull/242

### CODE REVIEW

**Comment by nazar-pc** [comment]
Identical Rust changes would be necessary for this to be merged

**Comment by ibc** [comment]
Don't do Rust changes yet, please. I need time to validate this. Having a ignoreNack setting shouldn't be needed. But I need time to properly comment.

**Comment by ibc** [comment]
Hi, here the ongoing PR for mediasoup. Almost done: https://github.com/versatica/mediasoup/pull/1015

**Comment by t-mullen** [comment]
Thanks @ibc 👍

**Pull request closed without merging**
