### PR TITLE
Worker: Add RTC::Shared singleton for RTC entities

### PR DESCRIPTION
**Pull request by ibc**
Avoid static/globals maps and classes exposing static methods. Instead, `Worker` creates a `RTC::Shared` singleton that is then passed down to all RTC entities.

The  `RTC::Shared` class includes:

```c++
public:
	ChannelMessageRegistrator* channelMessageRegistrator;
	Channel::ChannelNotifier* channelNotifier;
	PayloadChannel::PayloadChannelNotifier* payloadChannelNotifier;
```

### Bonus Tracks

* `Worker`: Avoid `Transport` emitting an event on behalf of a `DataConsumer` by adding `DataConsumer::SctpAssociationSendBufferFull()` method which is directly called from the `SctpAssociation`: https://github.com/versatica/mediasoup/pull/953/commits/5b72e059279ba5445043b052f9bdf4d228b69014

### CODE REVIEW

**Comment by jmillan** [comment]
This is gonna generate quite some conflicts on flatbuffers branch :-(

**Comment by ibc** [comment]
I'll fix the conflicts in your branch if this is approved, deal?

**Comment by jmillan** [comment]
I can, no problem. I'll review it a bit later today.

**Comment by jmillan** [comment]
Few comments from an initial review:

I don't have a better naming in mind right now, but `globals` sounds too generic for a class that is not so.

I think it would be clearer if this class would not just hold these three instances as a mere struct:

```c++
ChannelMessageRegistrator* channelMessageRegistrator,
Channel::ChannelNotifier* channelNotifier,
PayloadChannel::PayloadChannelNotifier* payloadChannelNotifier);
```

..., but expose an API with 4 simple methods:

```c++
* RegisterHandler();
* UnregisterHandler();
* Notify(); // Instead of Emit.
* NotifyPayload() // Instead of Emit.
```

I'll keep checking, but I think it can be made claner.

**Comment by ibc** [comment]
> ..., but expose an API with 4 simple methods:
> 
> ```c++
> * RegisterHandler();
> * UnregisterHandler();
> * Notify(); // Instead of Emit.
> * NotifyPayload() // Instead of Emit.
> ```
> 
> I'll keep checking, but I think it can be made claner.

Definitely the idea behind this PR is not create yet another wrapper but to literally expose access to class singletons (that previously were classes with just static methods).

**Comment by jmillan** [comment]
> Definitely the idea behind this PR is ... to literally expose access to class singletons

I see, I see.

**Review by jmillan — COMMENTED** [review]
Not really happy about having a `globals` container passed around.

I understand the rationale and that accessing globals/singletons is not nice, and that it's preferable to pass objects through instances in a more controlled way.

At this moment I can't come with another solution, so I'm not going to be a blocker here...

**Review by jmillan — APPROVED** [review]

**Comment by ibc** [comment]
IMHO:

1. This is better than what we have in v3 (mesh of static methods that break the original design of the Worker).
2. We don't know how to make it even better.
3. We don't really know if it can be done better (there is nothing wrong in passing singletons down to other entities).
4. Bullet 1 is still true.

**Comment by ibc** [comment]
@nazar-pc any idea why Rust tests are failing with a SIGABRT? I dind't change anything that could produce this...

https://github.com/versatica/mediasoup/actions/runs/3445533500/jobs/5749357768

**Comment by ibc** [comment]
I can consistently reproduce [this SIGABRT crash](https://github.com/versatica/mediasoup/actions/runs/3445533500/jobs/5749357768) running `cargo test` locally, so there is something missing or wrong in this PR.

**Comment by ibc** [comment]
Actually I get a different crash locally:

```
$ cargo test --lib

   Compiling mediasoup-sys v0.5.3 (/Users/ibc/src/v3-mediasoup/worker)
   Compiling mediasoup v0.11.2 (/Users/ibc/src/v3-mediasoup/rust)
    Finished test [unoptimized + debuginfo] target(s) in 1m 46s
     Running unittests src/lib.rs (/Users/ibc/src/v3-mediasoup/target/debug/deps/mediasoup-de3f73623525d3e8)

running 27 tests
test ortc::tests::generate_router_rtp_capabilities_unsupported ... ok
test ortc::tests::generate_router_rtp_capabilities_too_many_codecs ... ok
test ortc::tests::generate_router_rtp_capabilities_succeeds ... ok
test ortc::tests::get_producer_rtp_parameters_mapping_unsupported ... ok
test data_structures::tests::dtls_fingerprint ... ok
test ortc::tests::get_producer_rtp_parameters_mapping_get_consumable_rtp_parameters_get_consumer_rtp_parameters_get_pipe_consumer_rtp_parameters_succeeds ... ok
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/Users/ibc/src/v3-mediasoup/target/debug/deps/mediasoup-de3f73623525d3e8` (signal: 11, SIGSEGV: invalid memory reference)
```

```
rashed Thread:        45  mediasoup-worker-6cca8277-c4b8-45be-9f15-3b08d00e033d

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       UNKNOWN_0xD at 0x0000000000000000
Exception Codes:       0x000000000000000d, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [44121]
```

```
Thread 45 Crashed:: mediasoup-worker-6cca8277-c4b8-45be-9f15-3b08d00e033d
0   mediasoup-de3f73623525d3e8    	       0x10eb2514c absl::lts_20211102::container_internal::raw_hash_set<absl::lts_20211102::container_internal::FlatHashMapPolicy<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Channel::ChannelSocket::RequestHandler*>, absl::lts_20211102::container_internal::StringHash, absl::lts_20211102::container_internal::StringEq, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, Channel::ChannelSocket::RequestHandler*> > >::prefetch_heap_block() const + 12
1   mediasoup-de3f73623525d3e8    	       0x10eb2278d absl::lts_20211102::container_internal::raw_hash_set<absl::lts_20211102::container_internal::FlatHashMapPolicy<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Channel::ChannelSocket::RequestHandler*>, absl::lts_20211102::container_internal::StringHash, absl::lts_20211102::container_internal::StringEq, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, Channel::ChannelSocket::RequestHandler*> > >::iterator absl::lts_20211102::container_internal::raw_hash_set<absl::lts_20211102::container_internal::FlatHashMapPolicy<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Channel::ChannelSocket::RequestHandler*>, absl::lts_20211102::container_internal::StringHash, absl::lts_20211102::container_internal::StringEq, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, Channel::ChannelSocket::RequestHandler*> > >::find<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 29
2   mediasoup-de3f73623525d3e8    	       0x10eb228f1 unsigned long absl::lts_20211102::container_internal::raw_hash_set<absl::lts_20211102::container_internal::FlatHashMapPolicy<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Channel::ChannelSocket::RequestHandler*>, absl::lts_20211102::container_internal::StringHash, absl::lts_20211102::container_internal::StringEq, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, Channel::ChannelSocket::RequestHandler*> > >::erase<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 33
3   mediasoup-de3f73623525d3e8    	       0x10eb22b31 ChannelMessageRegistrator::UnregisterHandler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 33
4   mediasoup-de3f73623525d3e8    	       0x10ec1c22a RTC::Router::~Router() + 74
5   mediasoup-de3f73623525d3e8    	       0x10ec1d525 RTC::Router::~Router() + 21
6   mediasoup-de3f73623525d3e8    	       0x10ec1d589 RTC::Router::~Router() + 25
7   mediasoup-de3f73623525d3e8    	       0x10eb0b7e5 Worker::Close() + 277
8   mediasoup-de3f73623525d3e8    	       0x10eb0f0a6 Worker::HandleRequest(Channel::ChannelRequest*) + 118
9   mediasoup-de3f73623525d3e8    	       0x10eb562bf Channel::ChannelSocket::CallbackRead() + 191
10  mediasoup-de3f73623525d3e8    	       0x10eb55c38 Channel::onAsync(uv_handle_s*) + 24
11  mediasoup-de3f73623525d3e8    	       0x10f0b361f uv__async_io + 783
12  mediasoup-de3f73623525d3e8    	       0x10f0c1076 uv__io_poll + 4390
13  mediasoup-de3f73623525d3e8    	       0x10f0b3b5b uv_run + 267
14  mediasoup-de3f73623525d3e8    	       0x10eaf67c8 DepLibUV::RunLoop() + 120
15  mediasoup-de3f73623525d3e8    	       0x10eb0b2d3 Worker::Worker(Channel::ChannelSocket*, PayloadChannel::PayloadChannelSocket*) + 579
16  mediasoup-de3f73623525d3e8    	       0x10eb0b585 Worker::Worker(Channel::ChannelSocket*, PayloadChannel::PayloadChannelSocket*) + 37
17  mediasoup-de3f73623525d3e8    	       0x10eaf28b7 mediasoup_worker_run + 2295
18  mediasoup-de3f73623525d3e8    	       0x10e5ecee2 mediasoup::worker::utils::run_worker_with_channels::_$u7b$$u7b$closure$u7d$$u7d$::h48a30f751dfc61bf + 1650 (utils.rs:95)
19  mediasoup-de3f73623525d3e8    	       0x10e89794b std::sys_common::backtrace::__rust_begin_short_backtrace::h89f012974e9e4a53 + 43 (backtrace.rs:122)
20  mediasoup-de3f73623525d3e8    	       0x10e5c583b std::thread::Builder::spawn_unchecked_::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf93b220f289d62f2 + 43 (mod.rs:498)
21  mediasoup-de3f73623525d3e8    	       0x10e6a668b _$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h915c8d19fa4ed104 + 43 (unwind_safe.rs:271)
22  mediasoup-de3f73623525d3e8    	       0x10e9c929a std::panicking::try::do_call::hea5bf280840db446 + 74 (panicking.rs:492)
23  mediasoup-de3f73623525d3e8    	       0x10e9c93ed __rust_try + 29
24  mediasoup-de3f73623525d3e8    	       0x10e9c9068 std::panicking::try::h44e4e3189067e56d + 136 (panicking.rs:456)
25  mediasoup-de3f73623525d3e8    	       0x10ea85afb std::panic::catch_unwind::h7928747361f10de1 + 43 (panic.rs:137)
26  mediasoup-de3f73623525d3e8    	       0x10e5c5662 std::thread::Builder::spawn_unchecked_::_$u7b$$u7b$closure$u7d$$u7d$::hb3b05a01a590bcd2 + 370 (mod.rs:497)
27  mediasoup-de3f73623525d3e8    	       0x10ea2ab91 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h33288234316f15b9 + 17 (function.rs:227)
28  mediasoup-de3f73623525d3e8    	       0x10f4897c7 std::sys::unix::thread::Thread::new::thread_start::h1200bb61a12d3334 + 39
29  libsystem_pthread.dylib       	    0x7ff81f85c4e1 _pthread_start + 125
30  libsystem_pthread.dylib       	    0x7ff81f857f6b thread_start + 15
```

**Comment by ibc** [comment]
I know why.

**Comment by ibc** [comment]
Fixed.

**Comment by ibc** [comment]
@nazar-pc any thoughts about this PR? Only thing that @jmillan (and me) don't like is the `Globals` name. However no better name comes to our minds. This is not a "handler", a "manager", a "tool", a "helper", a "util", etc. This is just a singleton that is passed down to all RTC entities and gives them access to other singletons:

```c++
ChannelMessageRegistrator* channelMessageRegistrator
Channel::ChannelNotifier* channelNotifier
PayloadChannel::PayloadChannelNotifier* payloadChannelNotifier
```

Some random naming suggestions I don't really like:

- `RtcShared`
- `RtcTools`
- `RtcGlobals`

**Comment by ibc** [comment]
I'll rename it to `RTC::Shared`.

**Pull request merged**
